::Const.Strings.PerkDescription.LegendAthlete <- "You're a well-rounded athlete!\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Sprint[/color] skill which allows you to quickly cover four tiles in a straight line.\n\n• Does not work across rough terrain or through enemy zones of control.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]5[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]25[/color] Fatigue \n\n• Additionally, unlock the [color=" + ::Const.UI.Color.Skill + "]Climb[/color] skill which allows you to climb sheer cliffs up to five levels of height in one action.\n\n• Does not trigger attacks of opportunity.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]20[/color] Fatigue.\n\n• Picking the perk will also add [color=" + ::Const.UI.Color.Perk + "]Furinkazan[/color] to your perk map, which reduces the cost of [color=" + ::Const.UI.Color.Skill + "]Sprint[/color] and [color=" + ::Const.UI.Color.Skill + "]Climb[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendAthlete].Tooltip = ::Const.Strings.PerkDescription.LegendAthlete;

// ::Const.Strings.PerkDescription.LegendSmashingShields = "\'If you can\'t get around it, try smashing through. It works!\'\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Abilities targeting Shields do [color=" + ::Const.UI.Color.PositiveValue + "]100%[/color] increased damage.\n\n• If a Shield is destroyed by [color=" + ::Const.UI.Color.Skill + "]Split Shield[/color], recover [color=" + ::Const.UI.Color.PositiveValue + "]4[/color] Action Points and [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] of the Fatigue cost.";
// ::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSmashingShields].Tooltip = ::Const.Strings.PerkDescription.LegendSmashingShields;

::Const.Strings.PerkDescription.LegendSmackdown = "Use your size and strength to bully your way into a prime position.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color] \n• Effectiveness vs Armor is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color]. The bonus is increased to [color=" + ::Const.UI.Color.PositiveValue + "]+30%[/color] for Two-Handed Weapons.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Wind Up[/color] skill which prepares your next attack to [color=" + ::Const.UI.Color.Status + "]Knock Back[/color] and [color=" + ::Const.UI.Color.Status + "]Baffle[/color] your target on hit.\n• [color=" + ::Const.UI.Color.Status + "]Baffled[/color] enemies suffer [color=" + this.Const.UI.Color.NegativeValue + "]-15%[/color] Damage, Fatigue, and Initiative.\n\n• Additionally, on hit, reduce targets AP by [color=" + ::Const.UI.Color.NegativeValue + "]2[/color] for two turns.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]2[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]10[/color] Fatigue.\n\n• AP cost is reduced to [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] if wielding a Two-Handed Melee weapon. Works only with melee weapons, unarmed attacks and one handed slings. With one handed slings it will grant the [color=" + ::Const.UI.Color.Skill + "]Prepare Bullet[/color] effect.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSmackdown].Tooltip = ::Const.Strings.PerkDescription.LegendSmackdown;

if (::Is_PTR_Exist)
{
	::Const.Strings.PerkDescription.LegendSpecStaffStun = "Master the movements required to spin your staff in a great flourish so that it lands with additional force.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Any strike with a Staff or Sling-Staff that would normally [color=" + ::Const.UI.Color.Status + "]Daze[/color], also [color=" + ::Const.UI.Color.Status + "]Stuns[/color] and [color=" + ::Const.UI.Color.Status + "]Staggers[/color]. This does not apply to AoE attacks.\n\n• Staff Sweep now applies [color=" + ::Const.UI.Color.Status + "]Dazed[/color].\n\n• [color=" + ::Const.UI.Color.Skill + "]Whack a\' Smack[/color] gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit.";
}
else
{
	::Const.Strings.PerkDescription.LegendSpecStaffStun = "Master the movements required to spin your staff in a great flourish so that it lands with additional force.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Any strike with a Staff or Sling-Staff that would normally [color=" + ::Const.UI.Color.Status + "]Daze[/color], also [color=" + ::Const.UI.Color.Status + "]Stuns[/color] and [color=" + ::Const.UI.Color.Status + "]Staggers[/color]. This does not apply to AoE attacks.\n\n• Staff Sweep now applies [color=" + ::Const.UI.Color.Status + "]Dazed[/color].";
}
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecStaffStun].Tooltip = ::Const.Strings.PerkDescription.LegendSpecStaffStun;

::Const.Strings.PerkDescription.LegendTumble = "Make use of your acrobatic skill to improve your movements.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Reduces the Fatigue Cost of [color=" + ::Const.UI.Color.Skill + "]Lunge[/color], [color=" + ::Const.UI.Color.Skill + "]Footwork[/color], [color=" + ::Const.UI.Color.Skill + "]Leap[/color], [color=" + ::Const.UI.Color.Skill + "]Sprint[/color], [color=" + ::Const.UI.Color.Skill + "]Evasion[/color], and [color=" + ::Const.UI.Color.Skill + "]Audacious Charge[/color] by [color=" + ::Const.UI.Color.NegativeValue + "]50%[/color].\n\n• The Action Point cost of all these skills, except [color=" + ::Const.UI.Color.Skill + "]Lunge[/color], is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] and that of [color=" + ::Const.UI.Color.Skill + "]Leap[/color] is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]3[/color].\n\n• This is an upgraded version of [color=" + ::Const.UI.Color.Perk + "]Furinkazan[/color] and is not stackable.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendTumble].Tooltip = ::Const.Strings.PerkDescription.LegendTumble;

::Const.Strings.PerkDescription.LegendLastStand = "\'This is the hill that you will NOT die on!\'\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+1[/color] additional Melee and Ranged Defense for every [color=" + ::Const.UI.Color.NegativeValue + "]2%[/color] of missing Hitpoints below [color=" + ::Const.UI.Color.NegativeValue + "]66%[/color]\n\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+1[/color] additional Action Points for every [color=" + ::Const.UI.Color.NegativeValue + "]20%[/color] of missing Hitpoints.\n\n• When below [color=" + ::Const.UI.Color.NegativeValue + "]44%[/color] Hitpoints this character becomes immune to the effects of subsequent injuries, and moral is no longer affected by health loss.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendLastStand].Tooltip = ::Const.Strings.PerkDescription.LegendLastStand;

::Const.Strings.PerkDescription.Indomitable = "\'Mountains cannot be moved, nor taken down!\'\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Indomitable[/color] skill which grants a [color=" + ::Const.UI.Color.NegativeValue + "]50%[/color] damage reduction, as well as immunity to being [color=" + ::Const.UI.Color.Status + "]Stunned[/color], [color=" + ::Const.UI.Color.Status + "]Knocked Back[/color], [color=" + ::Const.UI.Color.Status + "]Grabbed[/color], or [color=" + ::Const.UI.Color.Status + "]Swallowed[/color] for one turn.\n\n• Base Resolve is [color=" + ::Const.UI.Color.PositiveValue + "]doubled[/color] until the effect ends.\n• Costs [color=" + ::Const.UI.Color.NegativeValue + "]5[/color] AP and [color=" + ::Const.UI.Color.NegativeValue + "]25[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Indomitable].Tooltip = ::Const.Strings.PerkDescription.Indomitable;

::Const.Strings.PerkDescription.LegendTwirl = "Practice in physical movement with a partner has given the ability to take the lead and move someone\'s body in a twirling movement.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n • The [color=" + ::Const.UI.Color.Skill + "]Rotation[/color] skill can now target enemies as well as allies. If you don't have [color=" + ::Const.UI.Color.Perk + "]Rotation[/color], taking this perk will grant you it for as long as you have this perk.\n\n• Picking the perk will also add [color=" + ::Const.UI.Color.Perk + "]Furinkazan[/color] to your perk map, which reduces the cost of [color=" + ::Const.UI.Color.Skill + "]Rotation[/color].\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]25[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendTwirl].Tooltip = ::Const.Strings.PerkDescription.LegendTwirl;

::Const.Strings.PerkDescription.QuickHands = "Looking for this?\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Swapping an item in battle becomes a free action with no Action Point cost, once every turn.\n\n• Does not work when swapping a Shield or between Two-Handed Melee Weapons.";
::Const.Perks.PerkDefObjects[::Legends.Perk.QuickHands].Tooltip = ::Const.Strings.PerkDescription.QuickHands;

::Const.Strings.PerkDescription.LegendMuscularity = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee or Throwing Weapon Attack[/color]\nPut your full weight into every blow!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain additional Minimum and Maximum Damage based on your current Hitpoints. \n\n• The bonus is [color=" + ::Const.UI.Color.PositiveValue + "]1.5%[/color] of your current Hitpoints per AP for attacks with a base Action Point cost of 5 or less, and [color=" + ::Const.UI.Color.PositiveValue + "]2%[/color] per AP for attacks with a base Action Point cost of 6 or more.\n\n• The factor is reduced to [color=" + ::Const.UI.Color.NegativeValue + "]60%[/color] for weapons that have a range of more than one tile and [color=" + ::Const.UI.Color.NegativeValue + "]80%[/color] for Daggers and Goblin Swords.\n\n• The bonus damage cannot be higher than [color=" + ::Const.UI.Color.PositiveValue + "]40[/color] for attacks with a base Action cost of 5 or less and [color=" + ::Const.UI.Color.PositiveValue + "]60[/color] for attacks with base AP cost of 6 or more.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendMuscularity].Tooltip = ::Const.Strings.PerkDescription.LegendMuscularity;

::Const.Strings.PerkDescription.Overwhelm = "Learn to take advantage of your initiative and prevent the enemy from attacking effectively by overwhelming them with your attacks!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active/Passive:[/u][/color]\n• With every attack, hit or miss, against an opponent that acts after you in the current round, inflict [color=" + ::Const.UI.Color.Status + "]Overwhelmed[/color] which lowers both Melee and Ranged Skill by [color=" + ::Const.UI.Color.NegativeValue + "]-10%[/color] for one turn.\n\n• The effect stacks with each attack, up to a maximum of 7 times, and can be applied to multiple targets at once with a single attack.\n\n• Additionally, unlocks the [color=" + ::Const.UI.Color.Skill + "]Quick Feint[/color] skill which allows you to apply [color=" + ::Const.UI.Color.Status + "]Overwhelmed[/color] to 4 adjacent targets, and can be used every other turn.\n\n• Costs [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] AP and [color=" + ::Const.UI.Color.NegativeValue + "]5[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Overwhelm].Tooltip = ::Const.Strings.PerkDescription.Overwhelm;

::Const.Strings.PerkDescription.LegendBattleheart = "Wade into the thick of battle, dodging blades from behind and above, aware of all around you at the heart of the battle.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Being surrounded no longer affects this character\'s Defenses at all.\n\n• Upgraded version of [color=" + ::Const.UI.Color.Perk + "]Underdog[/color], immune to [color=" + ::Const.UI.Color.Perk + "]Backstabber[/color].\n\n• Also prevents moral checks upon enemies entering your Zone of Control.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendBattleheart].Tooltip = ::Const.Strings.PerkDescription.LegendBattleheart;

::Const.Strings.PerkDescription.Underdog = "I\'m used to it.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The defense malus due to being surrounded by opponents is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]5[/color].\n\n• If an attacker has the [color=" + ::Const.UI.Color.Perk + "]Strength In Numbers[/color] perk, the effect of that perk is negated, and the normal defense malus due to being surrounded is applied instead.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Underdog].Tooltip = ::Const.Strings.PerkDescription.Underdog;

::Const.Strings.PerkDescription.SunderingStrikes = "Learn how to strike best at your targets\' Armor to destroy it as fast as possible.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Effectiveness against Armor is increased by [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color] of your weapon\'s Armor effectiveness.\n\n• The bonus is increased to [color=" + ::Const.UI.Color.PositiveValue + "]30%[/color] for Two-Handed Weapons.\n\n• When unarmed, effectiveness against Armor is increased by [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.SunderingStrikes].Tooltip = ::Const.Strings.PerkDescription.SunderingStrikes;

::Const.Strings.PerkName.LegendFullForce = "Immovable Object";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFullForce].Name = ::Const.Strings.PerkName.LegendFullForce;
::Const.Strings.PerkDescription.LegendFullForce = "Put your full weight into every blow!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] of the combined Fatigue modifier from body, head, main hand and off hand as additional melee Damage.\n\n• Additionally, gain a weakened [color=" + ::Const.UI.Color.Perk + "]Steadfast[/color] effect if the combined Fatigue modifier from body, head and off hand is [color=" + ::Const.UI.Color.PositiveValue + "]50[/color] or more.\n\n• This effect upgrades to the standard [color=" + ::Const.UI.Color.Perk + "]Steadfast[/color] once combined Fatigue is at [color=" + ::Const.UI.Color.PositiveValue + "]65[/color] or more.\n\n• Grants immunity to being [color=" + ::Const.UI.Color.Status + "]Stunned[/color] once the combined Fatigue modifier is at [color=" + ::Const.UI.Color.PositiveValue + "]80[/color] or more, stacking with the [color=" + ::Const.UI.Color.Perk + "]Steadfast[/color] effect.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFullForce].Tooltip = ::Const.Strings.PerkDescription.LegendFullForce;

::Const.Strings.PerkDescription.LegendShieldsUp <- "Drilling your troops in a shieldwall prepares their reaction time to avoid early deaths on the battlefield.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Taking this perk ensures every mercenary with a shield will use [color=" + ::Const.UI.Color.Skill + "]Shieldwall[/color] or [color=" + ::Const.UI.Color.Skill + "]Fortify[/color] before the start of each battle.";

::Const.Strings.PerkName.LegendSlaughterer = "Slaughterer";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSlaughterer].Name = ::Const.Strings.PerkName.LegendSlaughterer;
::Const.Strings.PerkDescription.LegendSlaughterer = "A gruesome display, enemies are more likely to lose morale when they witness their allies get split in two.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Melee kills are always fatalities.\n\n• Fatalaties have a [color=" + this.Const.UI.Color.NegativeValue + "]-10[/color] penalty to enemy Resolve checks.\n\n• Having the \'Bloodthirsty\' trait allows you to trigger an additional positive morale check when killing an enemy.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSlaughterer].Tooltip = ::Const.Strings.PerkDescription.LegendSlaughterer;

::Const.Strings.PerkDescription.LegendCheerOn = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Instrument or Banner[/color]\nUse your way with song to cheer on an ally!\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Cheer On[/color] skill which grants [color=" + ::Const.UI.Color.PositiveValue + "]+2[/color] Action Points to an adjacent ally.\n\n• Costs [color=" + ::Const.UI.Color.NegativeValue + "]3[/color] AP and [color=" + ::Const.UI.Color.NegativeValue + "]10[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendCheerOn].Tooltip = ::Const.Strings.PerkDescription.LegendCheerOn;

::Const.Strings.PerkDescription.LegendFavouredEnemyGhoul = ::Const.Strings.PerkDescription.LegendFavouredEnemyGhoul += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyGhoul].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyGhoul;

::Const.Strings.PerkDescription.LegendFavouredEnemyHexen = ::Const.Strings.PerkDescription.LegendFavouredEnemyHexen += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyHexen].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyHexen;

::Const.Strings.PerkDescription.LegendFavouredEnemyAlps = ::Const.Strings.PerkDescription.LegendFavouredEnemyAlps += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyAlps].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyAlps;

::Const.Strings.PerkDescription.LegendFavouredEnemyUnhold = ::Const.Strings.PerkDescription.LegendFavouredEnemyUnhold += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyUnhold].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyUnhold;

::Const.Strings.PerkDescription.LegendFavouredEnemyLindwurm = ::Const.Strings.PerkDescription.LegendFavouredEnemyLindwurm += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyLindwurm].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyLindwurm;

::Const.Strings.PerkDescription.LegendFavouredEnemyDirewolf = ::Const.Strings.PerkDescription.LegendFavouredEnemyDirewolf += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyDirewolf].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyDirewolf;

::Const.Strings.PerkDescription.LegendFavouredEnemySpider = ::Const.Strings.PerkDescription.LegendFavouredEnemySpider += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemySpider].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySpider;

::Const.Strings.PerkDescription.LegendFavouredEnemySchrat = ::Const.Strings.PerkDescription.LegendFavouredEnemySchrat += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemySchrat].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySchrat;

::Const.Strings.PerkDescription.LegendFavouredEnemyOrk = ::Const.Strings.PerkDescription.LegendFavouredEnemyOrk += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyOrk].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyOrk;

::Const.Strings.PerkDescription.LegendFavouredEnemyGoblin = ::Const.Strings.PerkDescription.LegendFavouredEnemyGoblin += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyGoblin].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyGoblin;

::Const.Strings.PerkDescription.LegendFavouredEnemyVampire = ::Const.Strings.PerkDescription.LegendFavouredEnemyVampire += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyVampire].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyVampire;

::Const.Strings.PerkDescription.LegendFavouredEnemySkeleton = ::Const.Strings.PerkDescription.LegendFavouredEnemySkeleton += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemySkeleton].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySkeleton;

::Const.Strings.PerkDescription.LegendFavouredEnemyZombie = ::Const.Strings.PerkDescription.LegendFavouredEnemyZombie += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyZombie].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyZombie;

::Const.Strings.PerkDescription.LegendFavouredEnemyNoble = ::Const.Strings.PerkDescription.LegendFavouredEnemyNoble += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyNoble].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyNoble;

::Const.Strings.PerkDescription.LegendFavouredEnemyBandit = ::Const.Strings.PerkDescription.LegendFavouredEnemyBandit += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyBandit].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyBandit;

::Const.Strings.PerkDescription.LegendFavouredEnemyBarbarian = ::Const.Strings.PerkDescription.LegendFavouredEnemyBarbarian += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyBarbarian].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyBarbarian;

::Const.Strings.PerkDescription.LegendFavouredEnemySwordmaster = ::Const.Strings.PerkDescription.LegendFavouredEnemySwordmaster += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemySwordmaster].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySwordmaster;

::Const.Strings.PerkDescription.LegendFavouredEnemyMercenary = ::Const.Strings.PerkDescription.LegendFavouredEnemyMercenary += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyMercenary].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyMercenary;

::Const.Strings.PerkDescription.LegendFavouredEnemyCaravan = ::Const.Strings.PerkDescription.LegendFavouredEnemyCaravan += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyCaravan].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyCaravan;

::Const.Strings.PerkDescription.LegendFavouredEnemySoutherner = ::Const.Strings.PerkDescription.LegendFavouredEnemySoutherner += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemySoutherner].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySoutherner;

::Const.Strings.PerkDescription.LegendFavouredEnemyNomad = ::Const.Strings.PerkDescription.LegendFavouredEnemyNomad += "\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyNomad].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyNomad;

// Need to overwrite this directly because weird
::Const.Strings.PerkDescription.LegendFavouredEnemyArcher = "Many claim to be the greatest shot in the land, but none have outshot you yet.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Grants [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] base bonus to melee skill, ranged skill, and maximum damage while fighting archer archetypes.\n\n• Additionally, this bonus increases the more archer archetypes you kill and counts all kills made previously with this character retroactively.\n\n• Increase per kill:\n  - Master Archer | [color=" + this.Const.UI.Color.PositiveValue + "]+0.5%[/color]\n  - Bandit Marksman | [color=" + this.Const.UI.Color.PositiveValue + "]+0.125%[/color]\n  - Rabble Poacher | [color=" + this.Const.UI.Color.PositiveValue + "]+0.025%[/color]\n  - Bandit Poacher | [color=" + this.Const.UI.Color.PositiveValue + "]+0.0625%[/color]\n  - Militia Marksman | [color=" + this.Const.UI.Color.PositiveValue + "]+0.05%[/color]\n  - Arbalist | [color=" + this.Const.UI.Color.PositiveValue + "]+0.25%[/color]\n  - Slinger | [color=" + this.Const.UI.Color.PositiveValue + "]+0.0125%[/color]\n  - Goblin Ambusher | [color=" + this.Const.UI.Color.PositiveValue + "]+0.0125%[/color]\n  - Nomad Slinger | [color=" + this.Const.UI.Color.PositiveValue + "]+0.0125%[/color]\n  - Nomad Marksman | [color=" + this.Const.UI.Color.PositiveValue + "]+0.25%[/color]\n  - Gunner | [color=" + this.Const.UI.Color.PositiveValue + "]+0.25%[/color]\n  - Desert Stalker | [color=" + this.Const.UI.Color.PositiveValue + "]+0.5%[/color]\n\n• Also increases spawn rate of archer archetype champions.\n\n• Reduces the penalty for attacking targets behind cover by [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color].\n\n• Total bonus capped at 25%.\n\n• When this character reaches a bonus of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color], the perk point spent is refunded.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFavouredEnemyArcher].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyArcher;

::Const.Strings.PerkDescription.LegendInTheZone = "Use your Armor\'s blend of protection and mobility to punish your foes mistakes!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain a stacking buff that boosts your Melee Skill and Melee Damage by [color=" + this.Const.UI.Color.PositiveValue + "]0.5%[/color] up to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color].\n\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.5%[/color] when you dodge a Melee attack and lose [color=" + ::Const.UI.Color.PositiveValue + "]1%[/color] when you get hit by any attack.\n\n• When engaged in Melee, the Melee Damage bonus is doubled, up to a maximum of [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color], and the Melee Skill bonus is converted into Melee Defense instead.\n\n• If your Initiative is higher than twice your combined body and head Armor\'s penalty to Maximum Fatigue, you start the battle with stacks equal to your Armor\'s weight above 15.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendInTheZone].Tooltip = ::Const.Strings.PerkDescription.LegendInTheZone;

::Const.Strings.PerkDescription.LegendRebound = "Surpass your limits!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Fatigue regeneration is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] while over 75% fatigued.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendRebound].Tooltip = ::Const.Strings.PerkDescription.LegendRebound;

::Const.Strings.PerkName.LegendPiercingShot = "Piercing Shot";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendPiercingShot].Name = ::Const.Strings.PerkName.LegendPiercingShot;
::Const.Strings.PerkDescription.LegendPiercingShot = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Crossbow [/color]\nLaunch a shot so powerful it can hit two targets in a straight line.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active/Passive:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Piercing Bolt[/color] skill which allows you to fire a powerful shot that can pass through your target, dealing [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] damage to the enemy behind them.\n\n• Additionally, Handgonnes gain [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] range.\n\n• Costs [color=" + ::Const.UI.Color.NegativeValue + "]5[/color] AP and [color=" + ::Const.UI.Color.NegativeValue + "]20[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendPiercingShot].Tooltip = ::Const.Strings.PerkDescription.LegendPiercingShot;

::Const.Strings.PerkDescription.FastAdaption = "Adapt to your opponent\'s moves!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain an additional stacking [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] chance to hit with each attack that misses an opponent.\n\n• Upon landing a hit, the character will also recover 1 Action Point for every stack up to a maximum of 3 and the bonus will be reset. The refund cannot exceed the maximum Action Points.";
::Const.Perks.PerkDefObjects[::Legends.Perk.FastAdaption].Tooltip = ::Const.Strings.PerkDescription.FastAdaption;

::Const.Strings.PerkDescription.Fearsome = "Make them scatter and flee!\n\n[color=#4f1800][u]Passive:[/u][/color]\n• Any attack that inflicts at least [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] point of damage to Hitpoints triggers a morale check for the opponent with a penalty equal to [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] of your current Resolve.\n\n[color=" + this.Const.UI.Color.NegativeValue + "]Does not trigger multiple times from the same attacker on the same target in one attack.[/color]";


::Const.Strings.PerkDescription.Fearsome = "Make them scatter and flee!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Any attack that inflicts at least [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] point of damage to hitpoints triggers a morale check for the opponent with a penalty equal to [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] of your current Resolve.\n\n• A kill [color=" + ::Const.UI.Color.PositiveValue + "]triples[/color] this effect for your next attack, but if you miss the effect will be wasted.\n\n•[color=" + ::Const.UI.Color.NegativeValue + "] Does not trigger multiple times from the same attacker on the same target from a single attack[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.Fearsome].Tooltip = ::Const.Strings.PerkDescription.Fearsome;

::Const.Strings.PerkDescription.Adrenaline = "Seize the initiative!\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Adrenaline[/color] skill which puts you first in the turn order for the next round, allowing you another turn before your enemies.\n\n• Additionally adds [color=" + ::Const.UI.Color.Perk + "]Irresistible Impulse[/color] to your perk map, which grants additional benefits when using [color=" + ::Const.UI.Color.Skill + "]Adrenaline[/color].\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]20[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Adrenaline].Tooltip = ::Const.Strings.PerkDescription.Adrenaline;

::Const.Strings.PerkDescription.ReachAdvantage = "Learn to use the superior reach of large weapons to keep the enemy from getting close enough to land a good hit.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When hitting an enemy, gain [color=" + ::Const.UI.Color.PositiveValue + "]+100%[/color] of your Melee Skill as Melee Defense against them until waiting or ending your turn.\n\n• Also, attempt to prevent them from approaching your Zone of Control with an attack of opportunity until next turn with a damage reduction of [color=" + ::Const.UI.Color.NegativeValue + "]20%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.ReachAdvantage].Tooltip = ::Const.Strings.PerkDescription.ReachAdvantage;

::Const.Strings.PerkDescription.Footwork = "Work those feet!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Footwork[/color] skill which allows you to leave a Zone of Control without triggering free attacks by using skillful footwork.\n\n• The Fatigue Cost of the skill increases by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] for every 1 point of total penalty to maximum Fatigue from head and body Armor above 15, up to a maximum Fatigue Cost of [color=" + ::Const.UI.Color.NegativeValue + "]20[/color].\n\n• Picking the perk will also add [color=" + ::Const.UI.Color.Perk + "]Furinkazan[/color] to your perk map, which reduces the cost of [color=" + ::Const.UI.Color.Skill + "]Footwork[/color].\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]10[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Footwork].Tooltip = ::Const.Strings.PerkDescription.Footwork;

::Const.Strings.PerkDescription.Rotation = "Just like dancing with your nan when you were young.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Rotation[/color] skill which allows two characters to switch places while ignoring Zone of Control, as long as neither character is [color=" + ::Const.UI.Color.Status + "]Stunned[/color], [color=" + ::Const.UI.Color.Status + "]Rooted[/color] or otherwise disabled.\n\n• Picking this perk will also add [color=" + ::Const.UI.Color.Perk + "]Furinkazan[/color] to your perk map, which reduces the cost of [color=" + ::Const.UI.Color.Skill + "]Rotation[/color]\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]25[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Rotation].Tooltip = ::Const.Strings.PerkDescription.Rotation;

::Const.Strings.PerkDescription.LegendEvasion = "\'Excuse me\'\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Evasion[/color] skill which enables this character to move swiftly and safely through any Zone of Control for the next whole turn without incurring any free attacks.\n\n• Picking this perk will also add [color=" + ::Const.UI.Color.Perk + "]Furinkazan[/color] to your perk map, which reduces the cost of [color=" + ::Const.UI.Color.Skill + "]Evasion[/color]\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]30[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendEvasion].Tooltip = ::Const.Strings.PerkDescription.LegendEvasion;

::Const.Strings.PerkDescription.LegendUnarmedTraining = "Focusing on technique, form, and stances has given you greater control over your unarmed strikes.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Increases damage of [color=" + ::Const.UI.Color.Skill + "]Hand to Hand[/color] and [color=" + ::Const.UI.Color.Skill + "]Lunge[/color] skills by an amount equal to the sum of your current Hitpoints and Initiative divided by 25.\n\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]90%[/color] of that value as minimum damage and [color=" + ::Const.UI.Color.PositiveValue + "]100%[/color] as max damage\n\n• This Damage increase is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]50%[/color] if you have an item in your offhand and is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]80%[/color] with an item in your mainhand.\n\n• If you have [color=" + ::Const.UI.Color.Perk + "]Unarmed Mastery[/color] gain [color=" + ::Const.UI.Color.PositiveValue + "]+20%[/color] effectiveness against Armor.\n\n• [color=" + ::Const.UI.Color.Skill + "]Choke[/color] gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit and deals [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] more damage.\n\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Tackle[/color] skill.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendUnarmedTraining].Tooltip = ::Const.Strings.PerkDescription.LegendUnarmedTraining;

::Const.Strings.PerkDescription.LegendChoke = "Once an opponent is fatigued, it may be easier to choke them out than to fight through their Armor.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Choke[/color] skill when both hands are free.\n\n• [color=" + ::Const.UI.Color.Status + "]Choked[/color] enemies have their Fatigue Recovery reduced by [color=" + this.Const.UI.Color.NegativeValue + "]15[/color].\n\n• Damage inflicted is equal to the sum of your current Initiative divided by 4 and current Hitpoints divided by 5.\n\n• Hit chance determined by your target\'s Fatigue, [color=" + this.Const.UI.Color.NegativeValue + "]0%[/color] if they are fresh and [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] if they are exhausted.\n\n• For every point of your targets body Armor that exceeds 125, a penalty is applied to hit chance, up to a maximum of [color=" + this.Const.UI.Color.NegativeValue + "]35%[/color].\n\n• Hit chance is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] if your target is [color=" + ::Const.UI.Color.Status + "]Dazed[/color] or [color=" + ::Const.UI.Color.Status + "]Parried[/color], [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] if they are [color=" + ::Const.UI.Color.Status + "]Stunned[/color] or [color=" + ::Const.UI.Color.Status + "]Netted[/color], and [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] if they are [color=" + ::Const.UI.Color.Status + "]Grappled[/color] or [color=" + ::Const.UI.Color.Status + "]Sleeping[/color].\n\n• If your target is [color=" + ::Const.UI.Color.Status + "]Grappled[/color], damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color].\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]20[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendChoke].Tooltip = ::Const.Strings.PerkDescription.LegendChoke;

::Const.Strings.PerkDescription.LegendSpecUnarmed = "Master the martial arts of unarmed combat.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Reduces the Fatigue costs of [color=" + ::Const.UI.Color.Skill + "]Hand to Hand[/color], [color=" + ::Const.UI.Color.Skill + "]Kick[/color], [color=" + ::Const.UI.Color.Skill + "]Grapple[/color], and [color=" + ::Const.UI.Color.Skill + "]Tackle[/color] by [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color].\n\n• Lowers AP cost for [color=" + ::Const.UI.Color.Skill + "]Hand to Hand[/color] by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] and increases Fatigue inflicted by [color=" + this.Const.UI.Color.PositiveValue + "]5[/color].\n\n• [color=" + ::Const.UI.Color.Skill + "]Kick[/color] has its [color=" + ::Const.UI.Color.Status + "]Daze[/color] chance increased to [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] and hit chance increased by [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color].\n\n• [color=" + ::Const.UI.Color.Skill + "]Choke[/color] damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+50%[/color] when target is already [color=" + ::Const.UI.Color.Status + "]Choked[/color] or [color=" + ::Const.UI.Color.Skill + "]Grappled[/color].\n\n• [color=" + ::Const.UI.Color.Skill + "]Grapple[/color] now has a [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] chance to [color=" + ::Const.UI.Color.Status + "]Disarm[/color] on hit and the hit chance is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color].\n\n• [color=" + ::Const.UI.Color.Skill + "]Tackle[/color] gains [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecUnarmed].Tooltip = ::Const.Strings.PerkDescription.LegendSpecUnarmed;

::Const.Strings.PerkDescription.HoldOut = "Keep it together!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Any negative status effect with a finite duration (e.g., [color=" + ::Const.UI.Color.Status + "]Bleeding[/color], [color=" + ::Const.UI.Color.Status + "]Charmed[/color]) has its duration reduced to one turn.\n\n• Status effects that have their effects grow weaker over several turns (e.g. [color=" + ::Const.UI.Color.Status + "]Goblin Poison[/color]) are at their weakest state from the start.\n\n• Grants a [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] reduction to the effect of all negative statuses.\n\n• Raises the chance to survive being struck down and not killed from [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color] to [color=" + this.Const.UI.Color.PositiveValue + "]66%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.HoldOut].Tooltip = ::Const.Strings.PerkDescription.HoldOut;

::Const.Strings.PerkDescription.LegendBarterGreed <- "This character is keen to guard the horde of gold the company has accumulated — and intends to protect it with their life.\n\n[color=#4f1800][u]Passive:[/u][/color]\n• For every 10,000 crowns you have in your stash:\n- Gain [color=" + this.Const.UI.Color.PositiveValue + "]+1.5[/color] to Melee Skill and Ranged Skill.\n- Gain [color=" + this.Const.UI.Color.PositiveValue + "]+1.5[/color] as Melee Defense and Ranged Defense.\n- Gain [color=" + this.Const.UI.Color.PositiveValue + "]+2[/color] to Resolve.\n\n• The Bonus gained from Crowns above 80000 is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color].\n\n• Additionally, your global Barter is divided by [color=" + this.Const.UI.Color.NegativeValue + "](1 + Brothers with this perk)[/color] at all times.";


::Const.Strings.PerkDescription.LegendBarterGreed = "Lust for gold and self interest can be a double edged sword, an immediate benefit in one place, may come at the expense of others. \n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.06%[/color] of your gear value as Melee and Ranged Skill.\n\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.08%[/color] of your gear value as Resolve.\n\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.04%[/color] of your gear value as Melee and Ranged Defense.\n\n• This bonus will cap at [color=" + ::Const.UI.Color.PositiveValue + "]+20[/color].\n\n• Your global Barter is divided by [color=" + ::Const.UI.Color.NegativeValue + "](1 + Brothers with this perk)[/color] at all times.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendBarterGreed].Tooltip = ::Const.Strings.PerkDescription.LegendBarterGreed;

::Const.Strings.PerkDescription.LegendBalance = "Gain increased defense by balancing your Armor\'s weight and mobility.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+10[/color] Ranged Defense when wearing head and body Armor with a total weight of 15 or less.\n\n• Convert [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] Ranged Defense to Melee Defense for every 2 points that you exceed this value, but reduce the conversion by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] for every 10 points that your Current Initiative is below twice your total Armor weight.\n\n• Gain a third of the converted Melee Defense bonus back as Ranged Defense.\n\n• The penalty to Initiative from your accumulated Fatigue is also reduced by [color=" + ::Const.UI.Color.PositiveValue + "]30%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendBalance].Tooltip = ::Const.Strings.PerkDescription.LegendBalance;

::Const.Strings.PerkDescription.LegendLithe = "Specialize in Medium Armour! Not as nimble as some but more lithe than others!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Damage to Hitpoints and Armor are reduced by [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] when the total penalty to Maximum Fatigue from head and body Armor is between [color=" + ::Const.UI.Color.NegativeValue + "]25[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]35[/color].\n\n• Outside this range, the bonus drops exponentially.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendLithe].Tooltip = ::Const.Strings.PerkDescription.LegendLithe;

::Const.Strings.PerkDescription.Nimble = "Specialize in Light Armour! By nimbly dodging or deflecting blows, convert any hits to glancing hits.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Damage to Hitpoints is reduced by up to [color=" + ::Const.UI.Color.NegativeValue + "]60%[/color] and damage to Armor is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]half[/color] of that amount.\n\n• This bonus drops exponentially when wearing head and body Armor with a total penalty to Maximum Fatigue above 15.\n\n• Provides [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] extra injury threshold.\n\n• [color=" + ::Const.UI.Color.Perk + "]Brawny[/color] does not affect this perk.\n\n• Does not affect damage from mental attacks or status effects.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Nimble].Tooltip = ::Const.Strings.PerkDescription.Nimble;

::Const.Strings.PerkDescription.SpecThrowing = "Master throwing weapons to wound or kill the enemy before they even get close.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Skills build up [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color] of your Ranged Skill as additional Armor penetration and [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] of your Melee Skill as additional Armor effectiveness when attacking at a distance of three tiles or less.\n\n• Throwing Spear now ignores the damage reduction from [color=" + ::Const.UI.Color.Perk + "]Shield Expert[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.SpecThrowing].Tooltip = ::Const.Strings.PerkDescription.SpecThrowing;

::Const.Strings.PerkDescription.SpecFlail = "Master the flail and circumvent your opponent\'s defenses.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\n• [color=" + ::Const.UI.Color.Skill + "]Lash[/color] and [color=" + ::Const.UI.Color.Skill + "]Hail[/color] ignore the defense bonus of shields.\n\n• [color=" + ::Const.UI.Color.Skill + "]Pound[/color] ignores an additional [color=" + ::Const.UI.Color.PositiveValue + "]10%[/color] of Armor on hits to the head.\n\n• [color=" + ::Const.UI.Color.Skill + "]Thresh[/color] gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.";
::Const.Perks.PerkDefObjects[::Legends.Perk.SpecFlail].Tooltip = ::Const.Strings.PerkDescription.SpecFlail;

// ::Const.Strings.PerkDescription.LegendSpecialistButcher = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill while using a Butcher\'s Cleaver.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to One-Handed Cleavers, except Whips.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
// ::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistButcher].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistButcher;

//::Const.Strings.PerkDescription.LegendSpecialistHammerSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and [color=" + ::Const.UI.Color.PositiveValue + "]+40%[/color] Armor damage while using a Blacksmith\'s Hammer.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to other One-Handed Hammers.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistHammerSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistHammerSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistKnifeSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and [color=" + ::Const.UI.Color.PositiveValue + "]+40%[/color] Armor penetration while using a Knife or Shiv.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to other Daggers.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistKnifeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistKnifeSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistMilitiaSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill while using a Militia Spear, Ancient Spear or Wooden Spear.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to other spears.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistMilitiaSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistMilitiaSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistPickaxeSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill while using a Pickaxe.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to other Two-Handed Hammers..\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistPickaxeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPickaxeSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistPitchforkSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and [color=" + ::Const.UI.Color.PositiveValue + "]+25%[/color] Armor damage while using a Pitchfork, Wooden Pitchfork, Hoe, Scythe or Wooden Flail.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this perk applies to other Polearms and Banners.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistPitchforkSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPitchforkSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistShortbowSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] ranged skill and 25% Armor penetration while using a Shortbow, Wonky Bow or Boondock Bow.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to other Bows.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistShortbowSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShortbowSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistShovelSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and the \'Knock Out\' skill while using a Shovel.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this bonus Melee Skill applies to Two-Handed Maces.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistShovelSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShovelSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistWoodaxeSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill while using a Woodcutter\'s Axe or Saw.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this bonus Melee Skill applies to other Axes.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistWoodaxeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistWoodaxeSkill;
//
//::Const.Strings.PerkDescription.LegendSpecialistSickleSkill = "After years of relentless training, you have achieved mastery over your weapon.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] Melee Skill and [color=" + ::Const.UI.Color.PositiveValue + "]+25%[/color] Armor piercing while using a Sickle or Notched Blade.\n\n• [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] of this skill applies to one handed swords.\n\n• This percentage will grow from time with the company, rising by [color=" + ::Const.UI.Color.PositiveValue + "]5%[/color] each week until you hit 100%.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecialistSickleSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistSickleSkill;

::Const.Strings.PerkDescription.Bullseye = "Nailed it!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The penalty to hitchance when shooting at a target you have no clear line of fire to is reduced from [color=" + ::Const.UI.Color.NegativeValue + "]75%[/color] to [color=" + ::Const.UI.Color.NegativeValue + "]33%[/color] for ranged weapons.\n\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Mark Target[/color] skill.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]2[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]15[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.Bullseye].Tooltip = ::Const.Strings.PerkDescription.Bullseye;

::Const.Strings.PerkDescription.LegendLookout = "Learn to find your enemies before they find you.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• This Character\'s Vision is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] and the ranged penalty at night is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]50%[/color].\n\n• Will pause the game when an enemy party is discovered nearby while travelling, allowing the party to avoid ambushes.\n\n• While on duty in the scout tent they grant [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] scouting.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendLookout].Tooltip = ::Const.Strings.PerkDescription.LegendLookout;

::Const.Strings.PerkDescription.LegendNetRepair = "Many years spent repairing and packing nets allows you to create nets and wield them more effectively.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Unlocks the \'Net\' recipe in the crafting tent, which you can use to fix broken ones.\n\n• Grants [color=" + ::Const.UI.Color.PositiveValue + "]+10[/color] Melee Defense while holding a net and reduces the AP cost of throwing nets to [color=" + ::Const.UI.Color.NegativeValue + "]3[/color].\n\n• Ignore the weight of nets, both when equipped and in your bag.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendNetRepair].Tooltip = ::Const.Strings.PerkDescription.LegendNetRepair;

::Const.Strings.PerkDescription.LegendNetCasting = "Always keep a net handy!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Throw Portable Net[/color] skill which allows you to throw a makeshift net once per battle.\n\n• Increases the range of all nets by [color=" + ::Const.UI.Color.PositiveValue + "]2[/color] tiles.\n\n• Allows you to swap nets to and from your bag for no AP.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]25[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendNetCasting].Tooltip = ::Const.Strings.PerkDescription.LegendNetCasting;

::Const.Strings.PerkDescription.LegendMasteryNets = "You\'ve learned advanced net throwing techniques.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Reduce the Fatigue cost of throwing a net by [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color].\n\n• Makes throwing other tools such as pots more effective.\n\n• Nets you throw have a chance to be reusable in battle and can be picked up from the ground.\n\n• If the target breaks free:\n- Regular Nets have a " + ::Const.UI.getColorized("25%", ::Const.UI.Color.PositiveValue) + " chance to be reusable.\n- Reinforced Nets have a " + ::Const.UI.getColorized("50%", ::Const.UI.Color.PositiveValue) + " chance to be reusable.\n\n• If the target is killed before breaking free:\n- All nets have a " + ::Const.UI.getColorized("100%", ::Const.UI.Color.PositiveValue) + " chance to be reusable.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendMasteryNets].Tooltip = ::Const.Strings.PerkDescription.LegendMasteryNets;

::Const.Strings.PerkDescription.LegendEscapeArtist = "Others see it as magic, but your deft hands know better.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Grants a chance to dodge nets with Ranged Defense.\n\n• At the start of your turn, perform a free [color=" + ::Const.UI.Color.Skill + "]Break Free[/color] action.\n\n• Grants a baseline [color=" + ::Const.UI.Color.PositiveValue + "]95%[/color] chance to break yourself free from [color=" + ::Const.UI.Color.Status + "]Rooting[/color] effects, such as Nets and Webs.\n\n• Reduces the Action Point cost of breaking yourself and your allies free by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] and the Fatigue cost by [color=" + ::Const.UI.Color.NegativeValue + "]70%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendEscapeArtist].Tooltip = ::Const.Strings.PerkDescription.LegendEscapeArtist;

::Const.Strings.PerkDescription.LegendPackleader = "Dogs can instinctively identify a pack leader, and your knowledge of their habits allows you to become that leader.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Unlocks the ability to store additional dog items in your bags and use them in battle.\n\n• Grants each dog you unleash the [color=" + ::Const.UI.Color.Perk + "]Assured Conquest[/color] perk.\n\n• Increases the total Armor of unleashed dogs by [color=" + ::Const.UI.Color.PositiveValue + "]100%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendPackleader].Tooltip = ::Const.Strings.PerkDescription.LegendPackleader;

::Const.Strings.PerkDescription.LegendDogBreeder = "Intimate knowledge of dog care and conditions required for breeding allows you to successfully breed dogs.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Unlocks a recipe in the crafting tent for breeding dogs.\n\n• Grants each dog you unleash the [color=" + ::Const.UI.Color.Perk + "]Fast Adaption[/color] and [color=" + ::Const.UI.Color.Perk + "]Backswing[/color] perks.\n\n• Increases the Melee Skill of unleashed dogs by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDogBreeder].Tooltip = ::Const.Strings.PerkDescription.LegendDogBreeder;

::Const.Strings.PerkDescription.LegendDogHandling = "You have mastered the art of training dogs. In the heat of battle your hounds will respond and react to your commands.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Dog Handling[/color] skill which allows you to order dogs to attack, or defend allies.\n\n• Grants each dog you unleash the [color=" + ::Const.UI.Color.Perk + "]Overwhelm[/color] perk.\n\n• Increases the Melee Defense of unleashed dogs by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDogHandling].Tooltip = ::Const.Strings.PerkDescription.LegendDogHandling;

::Const.Strings.PerkDescription.LegendDogWhisperer = "You have a way with dogs, the bond you form with them imbues each dog with more confidence and strength, knowing that you are there gives them strength.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Grants each dog you unleash the [color=" + ::Const.UI.Color.Perk + "]Colossus[/color], [color=" + ::Const.UI.Color.Perk + "]Fortified Mind[/color], [color=" + ::Const.UI.Color.Perk + "]Underdog[/color], and [color=" + ::Const.UI.Color.Perk + "]Clarity[/color] perks.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDogWhisperer].Tooltip = ::Const.Strings.PerkDescription.LegendDogWhisperer;

::Const.Strings.PerkDescription.LegendDogMaster = "Your way with animals extends so far you can turn away dogs that would otherwise do you harm.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• By spending [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] item of food you can make a dog flee from battle.\n\n• The food item is chosen at random and the perk does not work if you have less than 25 food.\n\n• Additionally, grant each dog you unleash the [color=" + ::Const.UI.Color.Perk + "]Dodge[/color] perk.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]15[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDogMaster].Tooltip = ::Const.Strings.PerkDescription.LegendDogMaster;

::Const.Strings.PerkDescription.LegendFieldTreats = "Make liberal use of alcohol and food to motivate your mercenaries.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Spend [color=" + this.Const.UI.Color.NegativeValue + "]20[/color] food to take an ally from wavering to steady moral and reduces their current Fatigue by [color=" + ::Const.UI.Color.NegativeValue + "]-15%[/color]\n\n• Cannot be applied to someone who has already been treated this combat.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]15[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFieldTreats].Tooltip = ::Const.Strings.PerkDescription.LegendFieldTreats;

::Const.Strings.PerkDescription.LegendFieldTriage = "Spend medicine to heal an ally mid-battle.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Field Triage[/color] skill which allows you to spend medicine to heal up to [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color] of a unit\'s missing health during a battle.\n\n• Heals at a rate of [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] medicine for every [color=" + ::Const.UI.Color.PositiveValue + "]4[/color] Hitpoints.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]6[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]16[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFieldTriage].Tooltip = ::Const.Strings.PerkDescription.LegendFieldTriage;

::Const.Strings.PerkDescription.LegendFieldRepairs = "Spend tools to repair an allies Armor on the battlefield.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Field Repairs[/color] skill which allows you to spend tools to repair up to [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color] of a unit\'s missing Armor during a battle.\n\n• Repairs Armor at a rate of [color=" + ::Const.UI.Color.NegativeValue + "]3[/color] tools for every [color=" + ::Const.UI.Color.PositiveValue + "]10[/color] Armor\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]6[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]16[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendFieldRepairs].Tooltip = ::Const.Strings.PerkDescription.LegendFieldRepairs;

::Const.Strings.PerkDescription.LegendSpecBandage = "Master the art of bandaging mid-combat, using any cloth available.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Bandage[/color] skill which allows you to bandage your allies.\n\n• Can bandage while in a zone of control, and adds [color=" + ::Const.UI.Color.PositiveValue + "]+5[/color] Hitpoints on the target\'s following turn.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]10[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendSpecBandage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecBandage;

//::Const.Strings.PerkDescription.LegendDrumsOfWar = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Instrument[/color]\nLearn powerful rhythms that drive your allies on.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]War Chant[/color] skill which restores [color=" + ::Const.UI.Color.PositiveValue + "]+4[/color] Fatigue to every ally within eight tiles.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]8[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]30[/color] Fatigue.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDrumsOfWar].Tooltip = ::Const.Strings.PerkDescription.LegendDrumsOfWar;

//::Const.Strings.PerkDescription.LegendDrumsOfLife = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Instrument or Unarmed[/color]\nLearn powerful rhythms that drive your allies on.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Drums of Life[/color] skill which restores [color=" + ::Const.UI.Color.PositiveValue + "]+8[/color] health to every ally within eight tiles.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]8[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]30[/color] Fatigue.";
//::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDrumsOfLife].Tooltip = ::Const.Strings.PerkDescription.LegendDrumsOfLife;

::Const.Strings.PerkDescription.LegendThrowSand = "It's hard to fight with sand in your eyes.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Throw Dirt[/color] skill, which lets you throw dirt in the eyes of an enemy to [color=" + ::Const.UI.Color.Status + "]Distract[/color] them.\n\n• [color=" + ::Const.UI.Color.Status + "]Distracted[/color] enemies have [color=" + this.Const.UI.Color.NegativeValue + "]-35%[/color] Initiative and deal [color=" + this.Const.UI.Color.NegativeValue + "]-35%[/color] Damage.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]5[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendThrowSand].Tooltip = ::Const.Strings.PerkDescription.LegendThrowSand;

::Const.Strings.PerkDescription.LegendDebilitate = "Ankles, hands, elbows and knees, you've learned how to fight dirty to secure victory.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=" + ::Const.UI.Color.Skill + "]Debilitate[/color] skill which primes your next attack to [color=" + ::Const.UI.Color.Status + "]Cripple[/color] a target for three turns, reducing their ability to inflict damage by [color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] and increasing the damage they take by [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color].\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]2[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]15[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendDebilitate].Tooltip = ::Const.Strings.PerkDescription.LegendDebilitate;

::Const.Strings.PerkDescription.Duelist = "Become one with your weapon and go for the weak spots!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When wielding a one handed weapon and your off hand is empty or you're holding an offhand throwable item, an extra [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] of damage ignores armor.\n\n• Bucklers and parrying daggers gain half of this bonus.\n\n• An extra [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] of damage ignores armor when using Two Handed or Throwing Weapons and having the [color=" + ::Const.UI.Color.Perk + "]Grandslam[/color] perk, but will reduce Armor Penetration by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] for One Handed weapons.\n\n• Having [color=" + ::Const.UI.Color.Perk + "]Grandslam[/color] also increases Armor penetration and damage by [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] when Unarmed.",
::Const.Perks.PerkDefObjects[::Legends.Perk.Duelist].Tooltip = ::Const.Strings.PerkDescription.Duelist;

::Const.Strings.PerkDescription.LegendConservation = "Conduct profane rituals meant to stave off the passage of time, further preserving the means of your craft.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Reduces the daily medicine cost of maintaining Human Corpses, Bones, and other Carrion by [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendConservation].Tooltip = ::Const.Strings.PerkDescription.LegendConservation;

::Const.Strings.PerkDescription.LegendChainLightning = "Unleash an arcing barrage of lightning!\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks 'Chain Lightning' skill which inflicts damage to up to 3 enemies, dealing [color=" + this.Const.UI.Color.DamageValue + "]15-30[/color] damage which ignores armor.\n\n• Requires a mystic staff.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]7[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]50[/color] Fatigue.\n• If you have the \'Staff Mastery\' perk, reduce the AP cost by 2 and the base fatigue cost by [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color].";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendChainLightning].Tooltip = ::Const.Strings.PerkDescription.LegendChainLightning;

::Const.Strings.PerkDescription.LegendHoldTheLine = "'DON'T LET THEM BREAK THROUGH!'\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlocks the [color=#400080]Hold the Line[/color] skill which allows you to direct your troops to stand their ground, granting [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Defense and Resolve to all allies within four tiles for one turn.\n\n• Costs [color=" + this.Const.UI.Color.NegativeValue + "]5[/color] AP and [color=" + this.Const.UI.Color.NegativeValue + "]20[/color] Fatigue.";
::Const.Perks.PerkDefObjects[::Legends.Perk.LegendHoldTheLine].Tooltip = ::Const.Strings.PerkDescription.LegendHoldTheLine;


local poleWeaponStrings = [
	"SpecAxe",
	"SpecHammer",
	"SpecMace",
	"SpecPolearm",
	"SpecSpear"
];

foreach (s in poleWeaponStrings)
{
	::Const.Strings.PerkDescription[s] = ::MSU.String.replace(::Const.Strings.PerkDescription[s], "no longer has a penalty", "has a reduced penalty");
	::Const.Strings.PerkDescription[s] = ::MSU.String.replace(::Const.Strings.PerkDescription[s], "no longer have a penalty", "have a reduced penalty");
	::Const.Perks.PerkDefObjects[::Legends.Perk[s]].Tooltip = ::Const.Strings.PerkDescription[s];
}
