::Const.Strings.crSellsword_EliteNames <- [
	"William III",
	"John VI",
	"Roger de Flor",
	"Götz von Berlich",
	"Sir John Chandos",
	"Francisco II",
	"János VI",
	"Thomas Montagu",
	"Michael II",
	"Philip of Swabia",
	"Geoffrey Charny",
	"Gaspar Guzmán",
	"René of Anjou",
	"Bertrand de Born",
	"Guy of Lusignan",
	"Jean de Vienne",
	"James St. George",
	"Richard FitzGil",
	"Thibaut Chamgn",
	"Alfonso Albuque",
	"Juan de Cueva",
	"Charles of Anjou",
	"Stephen of Blois",
	"Philip III",
	"Fulk IV of Anjou",
	"Tancred Sicily",
	"Raymond Poiters",
	"Baldwin Boulogne",
	"Bohemond Taranto",
	"Stephen Tournai",
	"Henry de Bohun",
	"Conan Brittany",
	"Gilbert Clare",
	"Hubert de Burgh",
	"Ralph de Gael",
	"Richard Clare",
	"Simon de Montfort",
	"Richard V",
	"William of Ypres",
	"Robert de Vere",
	"John de Warenne",
	"Abyss de Cranes",
	"Emo of Cutter",
	"Breaky de Devo",
	"Son von Satan",
	"Rygar III",
	"Chiru of Hanguk",
	"Grenik de Slav"
];

::Const.Strings.crBaronNames <- [
	"Lord Charles",
	"Lord Louis",
	"Lord Carloman",
	"Lord Eudes",
	"Lord Robert",
	"Lord Raoul",
	"Lord Lothaire",
	"Lord Hugues",
	"Lord Henri",
	"Lord Philippe",
	"Lord Jean",
	"Lord NapoleonIer"
];

::Const.Strings.crBlacksmithNames <- [
	"Muradin",
	"Modimus",
	"Aegrim",
	"Vanndar",
	"Thane",
	"Baelgun",
	"Grim"
];

::Const.Strings.crBlacksmithTitles <- [
	"Bronzebeard",
	"Stormheart",
	"Flamebeard",
	"Stormpike",
	"Stonehearth",
	"Hammerfall",
	"Thunderbrew "
];

::Const.Strings.crPriestNames <- [
	"Muradin",
	"Modimus",
	"Aegrim",
	"Vanndar",
	"Thane",
	"Baelgun",
	"Grim"
];

::Const.Strings.crDesperadoNames <- [
	"Foltest",
	"Radovid",
	"Henselt",
	"Keira Metz",
	"Dijkstra",
	"Vernon Roche",
	"John Natalis",
	"Dandelion",
	"Thaler",
	"John Calveit",
	"Morvran Voorhis",
	"Stefan Skellen",
	"Cahir",
	"James Hind",
	"Cartouche",
	"Hannikel",
	"Eppelein",
	"Schinderhannes",
	"Boarische Hiasl",
	"Hans Kohlhase",
	"Mathias Kneibl"
];

::Const.Strings.crDesperadoTitles <- [
	"the Knight Slayer",
	"the Wolfhunter",
	"the Waking Flame",
	"the Dragonborn",
	"the Revager",
	"the Unchained Aggressor",
	"the Knightmare",
	"the Scourge Harverster",
	"the Infernal Guardian",
	"the Indomitable Fury",
	"the Conviction",
	"the Flame Bringer",
	"of the Nightfal",
	"the Ironbane",
	"of the Four Winds",
	"the Savage Hero",
	"the Vengeance Incarnate",
	"the Leper",
	"the Outlaw"
];

::Const.Strings.crHashshashinNames <- [
	"Abul Nuqoud",
	"Malik",
	"Kadar",
	"Ibn Jubayr",
	"Haytham",
	"Suleiman",
	"Manuel",
	"Yusuf"
];

::Const.Strings.crHashshashinTitles <- [
	"Ibn-La Ahad",
	"Vidic",
	"Al-Sayf",
	"ad-Din Sinan",
	"the Lionheart",
	"Hastings",
	"Savonarola",
	"Kaczmarek",
	"Barleti",
	"Tazim"
];

::Const.Strings.crBarbarianChampionNames <- [
	"Harald",
	"Hildr",
	"Raud",
	"Steinunn",
	"Egill",
	"Steinvor",
	"Thorkell",
	"Rusla",
	"Embla",
	"Hallfrid",
	"Hrodgeir",
	"Arinbjorn",
	"Tyrkir",
	"Sorli",
	"Stakar",
	"Authulf"
];

::Const.Strings.crBarbarianChampionTitles <- [
	"Bluetooth",
	"Fairhair",
	"Lodbrok",
	"Sighvatsdottir",
	"the Tall",
	"Skallagrimsson",
	"the White",
	"the Steel-Forged",
	"the Raven Cut",
	"the Menace",
	"the Giantslayer"
];

::Const.Strings.FemaleKnightNames <- [
	"Dame Jean",
	"Dame Eula",
	"Dame Hertha",
	"Dame Vennessa",
	"Dame Amber",
	"Dame Klee",
	"Dame Lisa",
	"Dame Sucrose",
	"Dame Klee",
	"Dame Noelle",
	"Dame Margaret",
	"Dame Maria",
	"Dame Centaurea",
	"Dame Senomy",
	"Dame Willow",
	"Dame Liz"
];

::Const.Strings.LightSwordsmanNames <- [
	"Johannes Liechtenauer",
	"Sigmund Ringeck",
	"Fiore dei Liberi",
	"Kamiizumi Nobutsuna",
	"Donald McBane",
	"Joseph Bologne",
	"Gyorgy Thury",
	"William Marshal",
	"Antonio Manciolino",
	"Camillo Agrippa",
	"Giacomo di Grassi",
	"Angelo Viggiani",
	"George Silver",
	"Henry de Sainct-Didier"
];

::Const.Strings.SergeantTitles <- [
	"the Defender of the Weak",
	"the Hardiness",
	"the Relentless Assault",
	"the Vengeance Aura",
	"the Steed of Glory",
	"the Softened Blows",
	"the Luminescence",
	"the Law and Order",
	"the Vim and Vigor",
	"the Lawbringer"
];

::Const.Strings.SellswordsNames <- [
	"William III",
	"John VI",
	"Roger de Flor",
	"Götz von Berlich",
	"Sir John Chandos",
	"Francisco II",
	"János VI",
	"Thomas Montagu",
	"Michael II",
	"Philip of Swabia",
	"Geoffrey Charny",
	"Gaspar Guzmán",
	"René of Anjou",
	"Bertrand de Born",
	"Guy of Lusignan",
	"Jean de Vienne",
	"James St. George",
	"Richard FitzGil",
	"Thibaut Chamgn",
	"Alfonso Albuque",
	"Juan de Cueva",
	"Charles of Anjou",
	"Stephen of Blois",
	"Philip III",
	"Fulk IV of Anjou",
	"Tancred Sicily",
	"Raymond Poiters",
	"Baldwin Boulogne",
	"Bohemond Taranto",
	"Stephen Tournai",
	"Henry de Bohun",
	"Conan Brittany",
	"Gilbert Clare",
	"Hubert de Burgh",
	"Ralph de Gael",
	"Richard Clare",
	"Simon de Montfort",
	"Richard V",
	"William of Ypres",
	"Robert de Vere",
	"John de Warenne",
	"Abyss de Cranes",
	"Emo of Cutter",
	"Breaky de Devo",
	"Son von Satan",
	"Rygar III",
	"Chiru of Hanguk",
	"Grenik de Slav"
];

::Const.Strings.DryadNames <- [
	"Thallos",
	"Nymor",
	"Sylvan",
	"Aelius",
	"Lior",
	"Faelon",
	"Eryndor",
	"Calanthor",
	"Isoldar",
	"Lysan",
	"Marisar",
	"Oran",
	"Tethyr",
	"Avenor",
	"Briarthorn",
	"Elowyn",
	"Faelorn",
	"Glyndor",
	"Hesperon",
	"Illyrion",
	"Junir",
	"Kael",
	"Lythan",
	"Miras",
	"Naidar",
	"Ophion",
	"Phaedron",
	"Quillar",
	"Roswyn",
	"Seraphor",
	"Talon",
	"Virel",
	"Wynor",
	"Xanthor",
	"Ysolde",
	"Zephyrus",
	"Bryndor",
	"Eirlan",
	"Melanthor",
	"Ondros",
	"Selenor",
	"Elyon",
	"Asteros",
	"Liraen",
	"Niar",
	"Orian",
	"Rhiandor",
	"Selindor",
	"Thalon",
	"Virelith"
];

::Const.Strings.WarlockTitles <- [
	"Twilight Vanquisher",
	"the Hallowed",
	"the Nightfall",
	"Of the Shattered Sun",
	"the Darkbinder",
	"the Somber",
	"the Defiler",
	"the Foul",
	"the Decrepit",
	"the Shadowlord"
];

::Const.Strings.crBerserkerTitles <- [
	"Fleshrender",
	"the Stormrider",
	"the Deathbringer",
	"Of the Vengeful",
	"the Darkbinder",
	"the Sundering",
	"Worldcarver",
	"Dire Reaver",
	"the Cyclone",
	"the Bloodcursed",
	"Fierce Adamantite Ravager",
	"the Skullcrusher",
	"the Thunderstorm"
];

::Const.Strings.SlayerNames <- [
	"the Lindwurm Hunter",
	"the Wurmhunter",
	"the Lizard Hunter",
	"the Lizard Slayer",
	"Woodstalker",
	"the Lindwurm Slayer",
	"the Unhold Slayer",
	"the Tracker",
	"the Trophyhunter",
	"the Hunter",
	"the Orc Slayer",
	"the Dragon Slayer"
];