::Const.Necro <- {
	ConditionLossPerSixHour = 0.125,
	NoMaintainedMult = 1.0,
	HasMaintainedMult = 0.1,
	UndeadType = {
		Zombie = 0,
		Skeleton = 1,
		Vampire = 2,
		Mummy = 3,
		Ghost = 4,
		Banshee = 5,
		DemonHound = 6,
		COUNT =	6
	},
	CommonUndeadBackgrounds = [
		"necro_ancient_auxiliary",
		"necro_embalmbed_slave",
		"necro_zombie",
		
		"necro_ancient_legionary",
		"necro_ancient_honour_guard",
		"necro_embalmbed_soldier",
		"necro_embalmbed_priest",
		"necro_necrosavant",
		"necro_fallen_hero"
	],
	GhostUndeadBackgrounds = [
		"necro_ghost",
		"necro_banshee",
		"necro_skeledog"
	],
	BossUndeadBackgrounds = [
		"necro_lorekeeper"
	],
	InjuryPermanent = [
		[	// zombie
			{
				ID = "injury.missing_nose",
				Script = "injury_permanent/missing_nose_injury"
			},
			{
				ID = "injury.missing_eye",
				Script = "injury_permanent/missing_eye_injury"
			},
			{
				ID = "injury.missing_ear",
				Script = "injury_permanent/missing_ear_injury"
			},
			{
				ID = "injury.missing_finger",
				Script = "injury_permanent/missing_finger_injury"
			},
			{
				ID = "injury.missing_hand",
				Script = "injury_permanent/missing_hand_injury"
			},
		],
		[	// skeleton
			{
				ID = "injury.missing_finger",
				Script = "injury_permanent/missing_finger_injury"
			},
			{
				ID = "injury.missing_hand",
				Script = "injury_permanent/missing_hand_injury"
			},
		],
		[], // vampire
		[	// mummy
			{
				ID = "injury.missing_ear",
				Script = "injury_permanent/missing_ear_injury"
			},
			{
				ID = "injury.missing_finger",
				Script = "injury_permanent/missing_finger_injury"
			},
			{
				ID = "injury.maimed_foot",
				Script = "injury_permanent/maimed_foot_injury"
			},
			{
				ID = "injury.broken_elbow_joint",
				Script = "injury_permanent/broken_elbow_joint_injury"
			},
			{
				ID = "injury.missing_hand",
				Script = "injury_permanent/missing_hand_injury"
			},
		],
		[], // ghost
		[], // banshee
		[	// skeledog
			{
				ID = "injury.maimed_foot",
				Script = "injury_permanent/maimed_foot_injury"
			},
			{
				ID = "injury.broken_elbow_joint",
				Script = "injury_permanent/broken_elbow_joint_injury"
			},
		],
	]
};

::Const.Tactical.Actor.NecroZombieDog <- {
	XP = 200,
	ActionPoints = 12,
	Hitpoints = 125,
	Bravery = 0,
	Stamina = 180,
	MeleeSkill = 60,
	RangedSkill = 0,
	MeleeDefense = 5,
	RangedDefense = 5,
	Initiative = 110,
	FatigueEffectMult = 0.1,
	MoraleEffectMult = 0.0,
	FatigueRecoveryRate = 20,
	Armor = [
		30,
		30
	]
};

::Const.Strings.DemonHoundNames <- [
	"Shadowfang",
	"Grimclaw",
	"Nightstalker",
	"Dreadhowl",
	"Blackheart",
	"Doomjaw",
	"Bloodmoon",
	"Shadowpaw",
	"Darkfang",
	"Midnight",
	"Deathshade",
	"Shadowthorn",
	"Grimfang",
	"Voidclaw",
	"Nightshade",
	"Darkpaw",
	"Deathhowl",
	"Shadowbite",
	"Grimshadow",
	"Voidfang",
	"Soulreaper",
	"Darkmoon",
	"Ebonclaw",
	"Shadowmaw",
	"Grimwraith",
	"Dreadclaw",
	"Nightfall",
	"Darkheart",
	"Blackclaw",
	"Doomhowl",
	"Deathfang",
	"Shadowscar",
	"Nightdread",
	"Eclipse",
	"Gloomsnarl",
	"Shadowgrip",
	"Darkstorm",
	"Grimmaw",
	"Duskrage",
	"Deathgloom",
	"Darkshade",
	"Nightwrath",
	"Shadowshade",
	"Ebonfang",
	"Doomclaw",
	"Deathshadow",
	"Blackwraith",
	"Grimdark",
	"Nightclaw",
	"Shadowwraith"
];

::Const.Strings.GhostNames <- [
	"Deth",
	"Aeren",
	"Blythe",
	"Phan",
	"Aberra",
	"Undine",
	"Auris",
	"Devo",
	"Angel",
	"Ethae",
	"Kindel",
	"Shayde",
	"Myst",
	"Ethe",
	"Charis",
	"Stray",
	"Eaven",
	"Spec",
	"Flo",
	"Devi",
	"Lloial",
	"Lite",
	"Gallo",
	"Aide",
	"Remane",
	"Aener",
	"Perris",
	"Guya",
	"Spryte",
	"Celeste",
	"Ellis",
	"Ora",
	"Faith",
	"Elyse"
];

::Const.Strings.GhostTitles <- [
	"the Haunting Specter",
	"the Malevolent Phantom",
	"the Sinister Apparition",
	"the Vengeful Shade",
	"the Dreadful Wraith",
	"the Cursed Spirit",
	"the Tormented Banshee",
	"the Eerie Poltergeist",
	"the Ghastly Revenant",
	"the Shadowy Banshee",
	"the Diabolical Entity",
	"the Sinister Specter",
	"the Maleficent Apparition",
	"the Wicked Phantom",
	"the Wretched Wraith",
	"the Forsaken Spirit",
	"the Malevolent Ghost",
	"the Sinister Shade",
	"the Ephemeral Fiend",
	"the Wicked Wight"
];

::Const.Strings.BansheeNames <- [
	"Angy",
	"Damia",
	"Mindy",
	"Temprence",
	"Azure",
	"Misty",
	"Guardia",
	"Natura",
	"Kendel",
	"Damya",
	"Essence",
	"Celeste",
	"Carisma",
	"Mortia",
	"Vissi",
	"Mallory",
	"Aurabelle",
	"Karmay",
	"Vexa",
	"Dove",
	"Blesse",
	"Dwelle",
	"Exme",
	"Auriel",
	"Zoe",
	"Chasity",
	"Eterna",
	"Aure",
	"Angelica",
	"Via",
	"Erie",
	"Mortitia",
	"Shay",
	"Ondine",
	"Lucy",
	"Auralee",
	"Topia"
];

::Const.Strings.BansheeTitles <- [
	"the Wailing Banshee",
	"the Sorrowful Spirit",
	"the Keening Specter",
	"the Ephemeral Wraith",
	"the Mourning Phantom",
	"the Lamenting Ghost",
	"the Wailing Wraith",
	"the Mourning Banshee",
	"the Sorrowful Shade",
	"the Keening Banshee",
	"the Eerie Emissary",
	"the Wretched Wail",
	"the Crying Apparition",
	"the Ephemeral Echo",
	"the Wailing Whisper",
	"the Sorrowful Siren",
	"the Mourning Maiden",
	"the Keening Cry",
	"the Eerie Enigma",
	"the Wretched Wail"
];

::Const.Strings.EmbalmedNames <- [
	"Ahhotep", 
	"Ahmose", 
	"Akhethetep", 
	"Amenemhat", 
	"Amenemope", 
	"Amenhotep", 
	"Amenirdis", 
	"Amenmose", 
	"Ameny", 
	"Ankhesenpepi", 
	"Djehuty", 
	"Harsiese", 
	"Henuttawy", 
	"Hetepheres", 
	"Hori", 
	"Huy", 
	"Iset", 
	"Isetemkheb", 
	"Isetnofret", 
	"Karomama", 
	"Khaemwaset", 
	"Khamererneb", 
	"Khenemet", 
	"Khentkaus", 
	"Kheti", 
	"Khnumhotep", 
	"Maatkare", 
	"Menkheperre", 
	"Mhepeshef", 
	"Mentuhotep", 
	"Meresankh", 
	"Meritamen", 
	"Meritites", 
	"Meqy", 
	"Meryre", 
	"Minmose", 
	"Neferkare", 
	"Nefernef", 
	"Nefertari", 
	"Neferu", 
	"Nimlot", 
	"Panehesy", 
	"Pedubastis", 
	"Psusennes", 
	"Ptahhotep", 
	"Ptahmose", 
	"Qar", 
	"Ramesses", 
	"Ramose", 
	"Sekhemrek", 
	"Senusret", 
	"Setepenre", 
	"Shoshenq", 
	"Siamun", 
	"Smendes", 
	"Sobekemsaf", 
	"Sobekhotep", 
	"Tentamun", 
	"Thutmose", 
	"Tiye", 
	"Usaqmontu"
];

::Const.Strings.FallenHero <- [
	"Ser Balor",
	"Ser Thorne",
	"Ser Reynald",
	"Ser Aldric",
	"Ser Garrick",
	"Ser Cedric",
	"Ser Lucian",
	"Ser Ragnar",
	"Ser Percival",
	"Ser Desmond",
	"Ser Harald",
	"Ser Marrok",
	"Ser Darian",
	"Ser Bran",
	"Ser Erasmus",
	"Ser Leofric",
	"Ser Mortimer",
	"Ser Thaddeus",
	"Ser Bram",
	"Ser Urien",
	"Ser Caelan",
	"Ser Oswin",
	"Ser Valerian",
	"Ser Eldric",
	"Ser Corvin",
	"Ser Declan",
	"Ser Fenrir",
	"Ser Gideon",
	"Ser Hadrian",
	"Ser Ignatius",
	"Ser Jorah",
	"Ser Kalen",
	"Ser Lysander",
	"Ser Maximus",
	"Ser Nathaniel",
	"Ser Oberon",
	"Ser Percival",
	"Ser Quintus",
	"Ser Roderick",
	"Ser Seraphim",
	"Ser Tarquin",
	"Ser Uther",
	"Ser Vortigern",
	"Ser Wulfric",
	"Ser Xander",
	"Ser Yorick",
	"Ser Zephyrus",
	"Ser Alistair",
	"Ser Benedict",
	"Ser Cyrus"
];

::Const.Strings.FallenHeroTitles <- [
	"the Blighted",
	"the Forsaken",
	"the Revenant",
	"the Lichborn",
	"the Rotting",
	"the Fleshless",
	"the Gravewalker",
	"the Deathless",
	"the Soulless",
	"the Tombguard",
	"the Lamented",
	"the Wight",
	"the Corpsebearer",
	"the Rotknight",
	"the Boneblade",
	"the Wraith",
	"the Fleshrender",
	"the Necroblade",
	"the Dreadlord",
	"the Sorrowful",
	"the Desolate",
	"the Gravekeeper",
	"the Reanimated",
	"the Lichknight",
	"the Haunted",
	"the Deathbound",
	"the Cursed",
	"the Gravelord",
	"the Hollow",
	"the Decaylord",
	"the Doombringer",
	"the Forsworn",
	"the Deathbringer",
	"the Gravebound",
	"the Necroknight",
	"the Oathbreaker",
	"the Phantom",
	"the Graveguard",
	"the Relentless",
	"the Spectral",
	"the Tombwalker",
	"the Unyielding",
	"the Vanquished",
	"the Wretched",
	"the Xombified",
	"the Yawning",
	"the Zombie Lord",
	"the Abominable",
	"the Blightbringer",
	"the Cryptkeeper"
];

::Const.Strings.LegionnaireNames <- [
	"Decimus",
	"Tiberius",
	"Marius",
	"Cassius",
	"Lucius",
	"Maximus",
	"Titus",
	"Octavius",
	"Antonius",
	"Quintus",
	"Julius",
	"Claudius",
	"Marcellus",
	"Flavius",
	"Gaius",
	"Lucianus",
	"Aurelius",
	"Fabius",
	"Marcus",
	"Cassian",
	"Cornelius",
	"Decianus",
	"Drusus",
	"Rufus",
	"Hadrian",
	"Decius",
	"Octavian",
	"Tiberian",
	"Valentinus",
	"Severus",
	"Vespasian",
	"Hadrianus",
	"Aurelius",
	"Antoninus",
	"Valerianus",
	"Marcellinus",
	"Valentinian",
	"Maximianus",
	"Titanius",
	"Claudianus",
	"Cassianus",
	"Domitianus",
	"Commodianus",
	"Valerianus",
	"Galerius",
	"Julianus",
	"Flavianus",
	"Honorius",
	"Valerianus",
	"Severianus",
	"Octavianus",
	"Tertius",
	"Tribonius",
	"Varianus",
	"Severinus",
	"Faustinus",
	"Proculus",
	"Valerius",
	"Quirinus",
	"Rusticus",
	"Urbicus",
	"Vitalianus",
	"Zephyrinus",
	"Zoticus",
	"Urbanus",
	"Fulvianus",
	"Zeno",
	"Vitalis",
	"Ulysses",
	"Hadrianus",
	"Antoninianus",
	"Vigilius",
	"Vindex",
	"Maximinus",
	"Didius",
	"Aemilianus",
	"Blandus",
	"Honoratus",
	"Ignatius",
	"Justinianus",
	"Laurentius",
	"Lucillianus",
	"Mauricius",
	"Nestorius",
	"Nicomedes",
	"Orontius",
	"Priscillianus",
	"Secundus",
	"Tacitus",
	"Taurus",
	"Urbanus",
	"Valentinianus",
	"Zacharias",
	"Nicanor",
	"Ovidius",
	"Paulus",
	"Quintilianus",
	"Septimianus",
	"Terentius"
];