::Const.Strings.PerkDescription.PTRDismemberment = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Cutting Damage[/color]\nChop chop!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The threshold to inflict injuries is reduced by a percentage equal to [color= " + this.Const.UI.Color.NegativeValue + "]30%[/color] of your Maximum Damage.\n• Inflict additional [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] damage against targets that have sustained any injury effects.\n• Cutting attacks can now inflict injuries on Undead.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRDismemberment].Tooltip = ::Const.Strings.PerkDescription.PTRDismemberment;

::Const.Strings.PerkDescription.PTRBetweenTheEyes = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee Attack[/color]\nLike splitting butter!\n\n[color=" + this.Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 1 AP and builds 15 Fatigue.\n• Allows you to gain [color=" + this.Const.UI.Color.PositiveValue + "]60%[/color] of your Melee Skill as additional chance to hit the head for your next attack. If the attack misses, the effect is wasted.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBetweenTheEyes].Tooltip = ::Const.Strings.PerkDescription.PTRBetweenTheEyes;

::Const.Strings.PerkDescription.PTRTargetPractice = "Time in training has allowed you to come up with an efficient way to organize your ammo, while increasing your accuracy!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Swapping quivers or bags of ammo never costs any Action Points.\n• Aimed Shot gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRTargetPractice].Tooltip = ::Const.Strings.PerkDescription.PTRTargetPractice;

::Const.Strings.PerkDescription.PTRArrowToTheKnee = "The bane of adventurers everywhere, an arrow to the knee is a surefire way to debilitate a target!\n\n[color=" + this.Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 2 AP and builds 15 Fatigue.\n• Causes all of your ranged attacks during a turn to apply a debuff on the target for [color=" + this.Const.UI.Color.NegativeValue + "]2[/color] turns, reducing their Melee and Ranged Defense by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] each and requiring them to spend [color=" + this.Const.UI.Color.NegativeValue + "]2[/color] additional Action Points per tile moved, this will also lower them [color=" + this.Const.UI.Color.NegativeValue + "]30%[/color] Initiative. These effects are halved on the second turn.\n• Arrows to the knee deal [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] reduced Ranged Damage, have a [color=" + this.Const.UI.Color.NegativeValue + "]0%[/color] chance to hit the head.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRArrowToTheKnee].Tooltip = ::Const.Strings.PerkDescription.PTRArrowToTheKnee;

::Const.Strings.PerkDescription.PTREyesUp = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Ranged Weapon[/color]\nRain down arrows upon your enemies from a higher angle, forcing them to divert their attention!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When targets are more than [color=" + this.Const.UI.Color.NegativeValue + "]4[/color] tiles from you, every attack, hit or miss, applies a stacking debuff on the target reducing their Melee Skill and Ranged Skill by [color=" + this.Const.UI.Color.PositiveValue + "]-5[/color] and Defenses by [color=" + this.Const.UI.Color.PositiveValue + "]-3[/color]. Effect lasts one turn.\n• Enemies adjacent to the primary target receive half a stack.\n• Can have a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]5[/color] stacks.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTREyesUp].Tooltip = ::Const.Strings.PerkDescription.PTREyesUp;

::Const.Strings.PerkDescription.PTRSwordlike = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Cleaver[/color]\nCleaver... sword... pretty much the same thing, right?\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The \'Cleave\' and \'Rend Flesh\' skill gain [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.\n• Skills from Cleavers gain [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] hitchance against bleeding targets.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwordlike].Tooltip = ::Const.Strings.PerkDescription.PTRSwordlike;

::Const.Strings.PerkDescription.PTRSanguinary = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee Attack[/color]\nWhy go for the body when the head is such a juicy target?\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The chance to inflict fatalities is increased by [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color]\n• Fatalities refund [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] of the Base Fatigue Cost of the skill used.\n• During your turn, every successful attack that applies Bleeding, or is against an already bleeding target, improves your Morale by one level, and fatalities instantly set the Morale to Confident.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSanguinary].Tooltip = ::Const.Strings.PerkDescription.PTRSanguinary;

::Const.Strings.PerkDescription.PTRBloodlust = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee Attack[/color]\nWhen surrounded by carnage, you feel revitalized and right at home!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• During your turn, every successful attack reduces current Fatigue by [color=" + this.Const.UI.Color.PositiveValue + "]6%[/color] per stack of Bleeding on the target (each subsequent stack decrease the effect by [color=" + this.Const.UI.Color.NegativeValue + "]1%[/color] to a minimum of [color=" + this.Const.UI.Color.PositiveValue + "]3%[/color]) and increases Fatigue Recovery by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] for one turn per stack of Bleeding on the target.\n• Bleeding inflicted by the attack, or killing a target, also counts towards the bonus.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBloodlust].Tooltip = ::Const.Strings.PerkDescription.PTRBloodlust;

::Const.Strings.PerkDescription.PTRMauler = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Cleaver[/color]\nFlesh is a canvas on which you paint!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Attacks do more HP damage, the less armor your target has. This bonus is [color=" + this.Const.UI.Color.PositiveValue + "]35%[/color] more damage at no armor, and [color=" + this.Const.UI.Color.PositiveValue + "]0%[/color] more damage at 100% armor remaining.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRMauler].Tooltip = ::Const.Strings.PerkDescription.PTRMauler;

::Const.Strings.PerkDescription.PTRTakeAim = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Crossbow or Firearm[/color]\nYou\'ve learned the value of taking time with your shots when the situation calls for it!\n\n[color=" + this.Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 0 AP and builds 5 Fatigue.\n• Applies to your next attack during the same turn.\n• For Crossbows, the attack ignores the hitchance penalty from obstacles and the shot cannot go astray.\n• For Handgonnes the attack has its Maximum Range increased by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] and if used at a shorter range, the area of effect is increased by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] instead.\n• For Fire Lances, \'Ignite\' will have a [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] chance to disarm enemies and hitchance is increased by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color].\n• The following ranged attack will build additional [color=" + this.Const.UI.Color.NegativeValue + "]10[/color] Fatigue when being aimed.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRTakeAim].Tooltip = ::Const.Strings.PerkDescription.PTRTakeAim;

::Const.Strings.PerkDescription.PTRPowerShot = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Crossbow or Firearm[/color]\nLearn where to aim to hinder your enemies the most!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Attacks from Crossbows and Firearms have a [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] chance to inflict Staggered for one turn, hits to the head always stagger targets.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRPowerShot].Tooltip = ::Const.Strings.PerkDescription.PTRPowerShot;

::Const.Strings.PerkDescription.PTRPrimalFear = "Nothing ruins your day quite like a jolt to the head!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Attacks that hit the head have a chance to drop the target\'s morale by 1 level, independent of regular morale checks. The base chance is [color=" + this.Const.UI.Color.PositiveValue + "]40%[/color] and is increased by the % of health missing on the target after the hit.\n• For every morale level dropped due to this perk, the base chance against that target is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]-10%[/color] for subsequent hits from this character.\n• Cannot bring the target\'s morale to Fleeing.\n• Each time you trigger this effect, gain [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]+40%[/color] chance to hit the head until end of this combat.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRPrimalFear].Tooltip = ::Const.Strings.PerkDescription.PTRPrimalFear;

::Const.Strings.PerkDescription.PTRMuscleMemory = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Crossbow or Firearm[/color]\nWindlass... crank... bolt... aim.. fire... repeat!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The Action Point Cost of reloading a Crossbow is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color].\n• And that of reloading a Handgonne is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]2[/color].\n• The damage of \'Ignite\' is increased by [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRMuscleMemory].Tooltip = ::Const.Strings.PerkDescription.PTRMuscleMemory;

::Const.Strings.PerkDescription.PTRBetweenTheRibs = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee Attack[/color]\nStriking when an enemy is distracted allows this character to aim for the vulnerable bits!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Chance to hit the head is decreased by [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color].\n• Attacks deal [color=" + this.Const.UI.Color.PositiveValue + "]3.5%[/color] more damage per ally surrounding the target.\n• Daggers in mainhand deal [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] instead.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBetweenTheRibs].Tooltip = ::Const.Strings.PerkDescription.PTRBetweenTheRibs;

::Const.Strings.PerkDescription.PTRLightWeapon = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Dagger[/color]\nTake advantage of your Dagger\'s light weight to maneuver around the battlefield faster than your enemies!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When using a Dagger, build up [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] less Fatigue and you gain [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] Action Points.\n• Only works with Daggers equipped in the Mainhand.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRLightWeapon].Tooltip = ::Const.Strings.PerkDescription.PTRLightWeapon;

::Const.Strings.PerkDescription.PTRSwiftStabs = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Non-Hybrid Dagger[/color]\nCreate an opening, then finish them!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• A successful attack with Daggers reduces the Action Point cost of all Dagger skills by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] to a minimum of [color=" + this.Const.UI.Color.NegativeValue + "]2[/color] for the remainder of this turn.\n• The effect expires upon missing an attack, switching your weapon, or using any skill that is not a Dagger attack.\n• Only works with Daggers equipped in the Mainhand.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwiftStabs].Tooltip = ::Const.Strings.PerkDescription.PTRSwiftStabs;

::Const.Strings.PerkDescription.PTRSmallTarget = "Training against melons of all types has given you a penchant for hitting heads!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The chance to hit the head is multiplied by [color=" + this.Const.UI.Color.PositiveValue + "]125%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSmallTarget].Tooltip = ::Const.Strings.PerkDescription.PTRSmallTarget;

::Const.Strings.PerkDescription.PTRFromAllSides = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Flail[/color]\nYou\'ve learned to use the unpredictable swings of your flail to keep your enemies guessing!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Successful hits from Flails progressively reduce the target's Melee Skill and Defense by a stacking [color=" + this.Const.UI.Color.NegativeValue + "]-3[/color].\n• The effect is doubled if the attacks hit the head.\n• Missed attacks reduce [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] instead. Targets lose [color=" + this.Const.UI.Color.NegativeValue + "]5[/color] stacks at the start and end of every turn.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRFromAllSides].Tooltip = ::Const.Strings.PerkDescription.PTRFromAllSides;

::Const.Strings.PerkDescription.PTRRattle = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Blunt Damage[/color]\nRattle your enemies to their bones to weaken them!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Every attack that hits armor and does at least [color=" + this.Const.UI.Color.NegativeValue + "]10[/color] damage to Hitpoints, applies a stacking Rattled effect which reduces the target\'s damage output by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] for [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] turn.\n• Two-Handed Hammers will apply 2 stacks.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRRattle].Tooltip = ::Const.Strings.PerkDescription.PTRRattle;

::Const.Strings.PerkDescription.PTRDeepImpact = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Blunt Damage[/color]\n\'Roll out the barrel, feel it in your bones!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Hitpoints damage mitigation due to remaining armor on your target is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] of your current effectiveness against armor plus [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color].\n• Blunt attacks can now apply injuries to the Undead.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRDeepImpact].Tooltip = ::Const.Strings.PerkDescription.PTRDeepImpact;

::Const.Strings.PerkDescription.PTRDismantle = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Hammer and Blunt Damage[/color]\nStrip them of their protection while they still wear it!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Every successful hit with a hammer causes the target to receive a stacking [color=" + this.Const.UI.Color.NegativeValue + "]+15%[/color] ([color=" + this.Const.UI.Color.NegativeValue + "]+30%[/color] for Two-Handed Hammers) additional damage ignoring armor from all sources for the remainder of the combat.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRDismantle].Tooltip = ::Const.Strings.PerkDescription.PTRDismantle;

::Const.Strings.PerkDescription.PTRDentArmor = "[color=" + this.Const.UI.Color.NegativeValue + "]Requires: Hammer[/color]\n\'Can\'t fight if they can\'t walk.\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Attacks from Hammers have a chance to dent the target's armor and apply stacks of debuff, each stack increases their Action Points Cost when moving a tile by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] and armor damage taken by [color=" + this.Const.UI.Color.NegativeValue + "]+10%[/color], up to [color=" + this.Const.UI.Color.NegativeValue + "]3[/color] stacks are valid at the same time.\n• Each attack applies [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] stacks for Two-Handed Hammers and [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] for One-Handed Hammers.\n• Only works when attacks hit armor whose maximum durability is greater than 200.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRDentArmor].Tooltip = ::Const.Strings.PerkDescription.PTRDentArmor;

::Const.Strings.PerkDescription.PTRPushIt = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Mace[/color]\nPut your weight into it!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Attacks that will try to stun an opponent with a Mace now also applies the Staggered effect.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRPushIt].Tooltip = ::Const.Strings.PerkDescription.PTRPushIt;

::Const.Strings.PerkDescription.PTRBearDown = "\'Give their \'ed a nice knock, then move in for the kill!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Damage against enemies who have suffered a negative status effect is increased by [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] per such status effect and damage received from them is decreased by the same amount.\n• Only Stunned, Staggered, Dazed, and Baffled count as valid negative status effectst for this perk.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBearDown].Tooltip = ::Const.Strings.PerkDescription.PTRBearDown;

::Const.Strings.PerkDescription.PTRBoneBreaker = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Mace and Blunt Damage[/color]\nSnap, crunch, crumble. Music to your ears!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When using a Mace, attacks that do at least [color=" + this.Const.UI.Color.NegativeValue + "]5[/color] damage to Hitpoints reduce the target's maximum Hitpoints by [color=" + this.Const.UI.Color.PositiveValue + "]8%[/color], up to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]5[/color] stacks.\n• Attacks that stun a target or are against an already stunned or rooted target and attacks that deal at least [color=" + this.Const.UI.Color.NegativeValue + "]40[/color] damage to Hitpoints or [color=" + this.Const.UI.Color.NegativeValue + "]15%[/color] of their maximum Health, will apply with an additional stack.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBoneBreaker].Tooltip = ::Const.Strings.PerkDescription.PTRBoneBreaker;

::Const.Strings.PerkDescription.PTRBolster = "Your battle brothers feel confident when you\'re there backing them up!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Increase the Resolve, Skills and Defenses of adjacent allies by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] of your Level, to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]4[/color].\n• If multiple users with this perk are present, only the highest bonus applies.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBolster].Tooltip = ::Const.Strings.PerkDescription.PTRBolster;

::Const.Strings.PerkDescription.PTRIntimidate = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Polearm[/color]\n\'Trust me, ye don\'t want to be on the other end of a spike on a pole!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Attacks from Polearms, hit or miss, reduce the Resolve of the target by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] of your Melee Skill.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRIntimidate].Tooltip = ::Const.Strings.PerkDescription.PTRIntimidate;

::Const.Strings.PerkDescription.PTRLongReach = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Polearm[/color]\n\n\'If the target is watchin\' the head of yer pike, they\'re sure not watchin\' their back!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When wielding a Polearm, enemies within 2 tiles are considered surrounded by you for the purposes of hit-chance bonus for any allies attacking that target\n• The bonus to hitchance for each ally surrounding and distracting your target in melee is increased by [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color]. Stacks with Backstabber.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRLongReach].Tooltip = ::Const.Strings.PerkDescription.PTRLongReach;

::Const.Strings.PerkDescription.PTRPointyEnd = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Piercing Damage, Melee Attack[/color]\nThe first lesson every fighter gets taught, stick \'em with the pointy end!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Melee piercing attacks against an enemy without a Shield gain [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit and weapon durability loss is decreased by [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRPointyEnd].Tooltip = ::Const.Strings.PerkDescription.PTRPointyEnd;

::Const.Strings.PerkDescription.PTRThroughTheGaps = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Piercing Damage, Melee Attack[/color]\nLearn to call your strikes and target gaps in your opponents\' armor!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Melee piercing attacks ignore an additional [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] of the target's armor.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRThroughTheGaps].Tooltip = ::Const.Strings.PerkDescription.PTRThroughTheGaps;

::Const.Strings.PerkDescription.PTRTwoForOne = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Spear[/color]\nPractice in Spear-handling has taught you to strike in the most efficient way possible!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When using a Spear, the Action Point cost of Thrust, Prong, Glaive Slash, Jab and Throw Javelin is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRTwoForOne].Tooltip = ::Const.Strings.PerkDescription.PTRTwoForOne;

::Const.Strings.PerkName.PTRABetterGrip = "A Better Grip";
::Const.Strings.PerkDescription.PTRABetterGrip = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Spear[/color]A Spear has a strong advantage. Reach advantage.\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When double-gripping One-Handed Spears, the range of Thrust is increased to 2 tiles. When used at this range, it does [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] reduced damage, has no bonus chance to hit, and has [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] chance to hit per character between you and the target.\n• When wielding two-handed Spears, attacks at 1 tiles range gain [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] hitchance.\n• When using a Spear, every successful hit against an opponent increases your Melee Skill and Melee Defense against that opponent by [color=" + this.Const.UI.Color.PositiveValue + "]+4[/color] up to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]+20[/color]. This bonus does not expire on its own but is lost upon taking damage from that opponent.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRABetterGrip].Name = ::Const.Strings.PerkName.PTRABetterGrip;
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRABetterGrip].Tooltip = ::Const.Strings.PerkDescription.PTRABetterGrip;

::Const.Strings.PerkDescription.PTRKingOfAllWeapons = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Spear[/color]\nOne King to rule them all!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When starting your turn with a Spear equipped, the first Thrust or Prong during your turn costs no Action Points and builds no Fatigue, but does [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] reduced Damage.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRKingOfAllWeapons].Tooltip = ::Const.Strings.PerkDescription.PTRKingOfAllWeapons;

::Const.Strings.PerkDescription.PTRExploitOpening = "A low Shield. A slobby stab. A fake stumble. All are ways that you\'ve learned to tempt your opponent into a fatal false move!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Whenever an opponent misses a Melee attack against you, they are affected by the \'Exploitable Opening\' effect until their next turn, which gives you [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] hit-chance and [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] armor penetration against them.\n• Makes the \'Riposte\' skill available on the Shamshir and One-Handed versions of Saif and Scimitar.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRExploitOpening].Tooltip = ::Const.Strings.PerkDescription.PTRExploitOpening;

::Const.Strings.PerkDescription.PTRFluidWeapon = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Sword[/color]\nA well-balanced sword is like an extension of yourself!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Initiative is increased by [color=" + ::Const.UI.Color.PositiveValue + "]35%[/color] of the currently equipped sword\'s armor ignore damage percentage.\n• The Fatigue Cost of weapon skills is reduced by [color=" + ::Const.UI.Color.NegativeValue + "]20%[/color] of the currently equipped sword\'s armor effectiveness.\n• Penalty to Initiative from Fatigue build-up is decreased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] of the currently equipped sword\'s maximum damage.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRFluidWeapon].Tooltip = ::Const.Strings.PerkDescription.PTRFluidWeapon;

::Const.Strings.PerkDescription.PTRTempo = "By keeping ahead of your opponent, you set the terms of engagement!\n\n\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Every attack against a target who acts after you in the current round increases your Initiative by [color=" + this.Const.UI.Color.PositiveValue + "]+15[/color], additionally Melee Skill and Melee Defense will increase by [color=" + this.Const.UI.Color.PositiveValue + "]+3[/color].\n• All bonus is decreased to [color=" + this.Const.UI.Color.NegativeValue + "]66%[/color] if you are not wielding pure swords.\n• These bonuses lasts over into your next turn but only until the first skill used or waiting that turn.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRTempo].Tooltip = ::Const.Strings.PerkDescription.PTRTempo;

::Const.Strings.PerkDescription.PTRFormidableApproach = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Two-Handed Melee Weapon[/color]\nMake them think twice about getting close!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When wielding a Two-Handed weapon, reduce the Melee Skill and Melee Defense of any enemy who enters your zone of control by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] of your Melee Skill, and half of that when hit enemies.\n• The debuff lasts until the enemy exits your zone of control or successfully hit you.\n• Only has half the effect against enemies with Two-Handed weapons and does not work if the enemy also has this perk.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRFormidableApproach].Tooltip = ::Const.Strings.PerkDescription.PTRFormidableApproach;

::Const.Strings.PerkDescription.PTRSweepingStrikes = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] AOE Attack[/color]\nForce your enemies to neglect offense with the sweeping swings of your weapon!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• AOE attacks lower the Melee Skill, Resolve and Damage of any target hit for one turn. This reduction is [color=" + this.Const.UI.Color.NegativeValue + "]15%[/color] for targets with One-Handed weapons and [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] for targets with Two-Handed weapons.\n• Only half of this reduction applies if you act after the target in the current round.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSweepingStrikes].Tooltip = ::Const.Strings.PerkDescription.PTRSweepingStrikes;

::Const.Strings.PerkDescription.PTRSkirmisher = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Throwing Weapon[/color]\nThey won\'t even see it comin\'!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The Action Point cost of the first [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] Throwing attacks during a combat are [color=" + this.Const.UI.Color.PositiveValue + "]halved[/color].\n• During your first turn, the Action Point cost of moving on any terrain is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] to a minimum of [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] and the Fatigue Cost is halved. These bonuses stack with the Pathfinder perk.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSkirmisher].Tooltip = ::Const.Strings.PerkDescription.PTRSkirmisher;

::Const.Strings.PerkDescription.PTROpportunist = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Throwing Weapon[/color]\n\'I\'m not lootin\' Captain! Just grabbing my javelin!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Every time you stand over an enemy's corpse, gain [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] ammo and restore [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] Action Points.\n• Also causes the next throwing attack to build up [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] less Fatigue. \n• Cannot trigger from the same corpse twice.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTROpportunist].Tooltip = ::Const.Strings.PerkDescription.PTROpportunist;

::Const.Strings.PerkDescription.PTRNailedIt = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Ranged Attack[/color]\n\'One javelin to the head will take \'em right out!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The chance to hit the head with ranged attacks is increased by [color=" + this.Const.UI.Color.PositiveValue + "]35%[/color] but reduced by [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] per tile of distance between you and the target.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRNailedIt].Tooltip = ::Const.Strings.PerkDescription.PTRNailedIt;

::Const.Strings.PerkDescription.PTRSurvivalInstinct = "Your will to live is strong!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Whenever you are attacked, gain a stacking bonus to Melee and Ranged Defense of [color=" + this.Const.UI.Color.PositiveValue + "]+2[/color] on a miss and [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] on a hit if it is less than [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] of your maximum Hitpoints. At the start of every turn the bonus is reset except the bonus gained from getting hit which is retained for the remainder of the combat. This retained bonus cannot be higher than [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSurvivalInstinct].Tooltip = ::Const.Strings.PerkDescription.PTRSurvivalInstinct;

::Const.Strings.PerkDescription.PTRKnowTheirWeakness = "The next one\'s gonna be even easier!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Once per turn, the first successful attack applies a negative status effect which decreases the target's defences and Resolve by [color=" + this.Const.UI.Color.NegativeValue + "]20%[/color] for 1 turn.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRKnowTheirWeakness].Tooltip = ::Const.Strings.PerkDescription.PTRKnowTheirWeakness;

::Const.Strings.PerkName.PTRDynamicDuo = "Delay";
::Const.Strings.PerkDescription.PTRDynamicDuo = "One a stalwart defender, and the other a prodigy with the blade. Time together has grown this into a well choreographed dance of death.\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain a special rotation skill-\'Delay\' which once per turn can be used on an ally with this same perk for free. Using \'Delay\' will transfer [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] of your melee and ranged skill, alongside [color=" + this.Const.UI.Color.PositiveValue + "]75%[/color] of your defences to the target ally until the end of the next turn.\n• Picking the perk will also add \'Furinkazan\' to your perk map, which reduces the AP cost of \'Delay\' to [color=" + this.Const.UI.Color.PositiveValue + "]0[/color].\n• Taking this perk stops you from hitting allies with your attacks.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRDynamicDuo].Name = ::Const.Strings.PerkName.PTRDynamicDuo;
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRDynamicDuo].Tooltip = ::Const.Strings.PerkDescription.PTRDynamicDuo;

::Const.Strings.PerkDescription.PTRVigorousAssault = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee, Throwing Weapon or Unarmed[/color]\nYou\'ve learned to use the very momentum of your movement as a weapon unto itself!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• For every 2 tiles moved, the Action Point cost of your next attack is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]1[/color] to a minimum of [color=" + this.Const.UI.Color.NegativeValue + "]2[/color], the Fatigue Cost is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] and Damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color].\n• The bonus is lost upon waiting, ending your turn, using any skill, or swapping your weapon except to or from a throwing weapon.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRVigorousAssault].Tooltip = ::Const.Strings.PerkDescription.PTRVigorousAssault;

::Const.Strings.PerkDescription.PTRUnstoppable = "Once you get going, you can\'t be stopped!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Once per turn, killing an enemy will grant [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] stacks.\n• Each stack increases Melee Skill by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] and Melee Damage by [color=" + this.Const.UI.Color.PositiveValue + "]1%[/color], up to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]30[/color] stacks.\n• You lose half of the stacks if you get hit and lose more than [color=" + this.Const.UI.Color.NegativeValue + "]20[/color] Hitpoints.";	
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRUnstoppable].Tooltip = ::Const.Strings.PerkDescription.PTRUnstoppable;

::Const.Strings.PerkDescription.PTRVigilant = "\'On the battlefield, you must always be ready to defend at a moment\'s notice, or strike at a narrow opportunity!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• At the end of your turn, gain Melee Defense and Ranged Defense based on your remaining Action Points and Fatigue percentage. The bonus lasts until the end of your next turn and ranges from [color=" + this.Const.UI.Color.PositiveValue + "]+0.5[/color] to [color=" + this.Const.UI.Color.PositiveValue + "]+2[/color] per action point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRVigilant].Tooltip = ::Const.Strings.PerkDescription.PTRVigilant;

::Const.Strings.PerkDescription.PTRPersonalArmor = "Give your own armor some of that special treatment!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Damage received to armour is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color].\n• Head and Body armour is increased by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRPersonalArmor].Tooltip = ::Const.Strings.PerkDescription.PTRPersonalArmor;

::Const.Strings.PerkDescription.PTRTunnelVision = "Years of working in dark mines has given you an advantage fighting at night!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• At night, vision is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+2[/color], Melee skill, Melee Defense and Resolve are increased by [color=" + this.Const.UI.Color.PositiveValue + "]10%[/color], Ranged skill and Defense are increased by [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRTunnelVision].Tooltip = ::Const.Strings.PerkDescription.PTRTunnelVision;

::Const.Strings.PerkDescription.PTRPromisedPotential = "The Captain said he\'d take a gamble on you, but you\'d better not disappoint!\n\n[color=" + this.Const.UI.Color.OneTimeEffect + "][u]One-Time Effect:[/u][/color]\n• This perk remains inert until level 11.\n• Upon reaching level 11, if this was the first perk bought, it will be replaced with \'Realized Potential\' which will double this character\'s salary, increase all attributes by [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] to [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color], unlock new perk groups, and refund all perk points, including the one spent on this perk.\n• If unsuccessful, it is replaced by \'Failed Potential\' which does nothing.\n• Perks obtained due to starting origin or background do not count towards failing your Potential.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRPromisedPotential].Tooltip = ::Const.Strings.PerkDescription.PTRPromisedPotential;

::Const.Strings.PerkDescription.PTRBulwark = "\'Not much to be afraid of behind a suit of plate!\'\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Resolve is increased by [color=" + this.Const.UI.Color.PositiveValue + "]2%[/color] of the combined current durability of head and body armor.\n• This bonus is [color=" + this.Const.UI.Color.PositiveValue + "]doubled[/color] against negative morale checks except mental attacks.\n• Hitpionts are increase by [color=" + this.Const.UI.Color.PositiveValue + "]2%[/color] of the combined maximum durability of head and body armor";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRBulwark].Tooltip = ::Const.Strings.PerkDescription.PTRBulwark;

::Const.Strings.PerkDescription.PTRManOfSteel = "\'S\' is the symbol for \'Hope\'.\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Hitpoints damage mitigation due to remaining armour durability after receiving a hit is increased by [color=" + this.Const.UI.Color.PositiveValue + "]66%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRManOfSteel].Tooltip = ::Const.Strings.PerkDescription.PTRManOfSteel;

::Const.Strings.PerkDescription.PTRWeaponMaster = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] One-Handed Melee or Throwing Weapon[/color]\nYou\'ve learned well that weapons are like tools, tailor-made to accomplish specific tasks. Therefore, you carry a small arsenal, ready to handle any situation!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Grants the bonuses of the weapon mastery perks for all One-Handed Melee and Throwing weapons whose perk groups this character has access to.\n• Once per turn, switching from a One-Handed Melee or Throwing weapon to another costs no Action Points and if you switched between the two, you gain a bonus that grants the next attack with a One-Handed Weapon a reduction of [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] Action Points.\n• Does not stack with Quick Hands.\n\nOnly works if you have picked at least one of the following weapon mastery perks: Axe, Cleaver, Dagger, Flail, Hammer, Mace, Spear, Sword, Throwing.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRWeaponMaster].Tooltip = ::Const.Strings.PerkDescription.PTRWeaponMaster;

::Const.Strings.PerkDescription.PTRMenacing = "Your appearance fills your enemies with terror!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Lower the Resolve of all adjacent enemies by [color=" + this.Const.UI.Color.PositiveValue + "]-5[/color]. This debuff will continue to stack each turn, up to a maximum of [color=" + this.Const.UI.Color.PositiveValue + "]-15[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRMenacing].Tooltip = ::Const.Strings.PerkDescription.PTRMenacing;

::Const.Strings.PerkDescription.PTRProfessional = "You\'re a professional, experienced soldier, able to fight with many weapons in many styles!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Grants the benefits of the Shield Expert, Bags and Belts, Duelist, Quick Hands, and Bloody Harvest perks without requiring these perks to be picked.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRProfessional].Tooltip = ::Const.Strings.PerkDescription.PTRProfessional;

::Const.Strings.PerkDescription.PTRSavageStrength ="Orcs call me brother!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The extra Fatigue build-up on skills from weapons such as Orc Weapons is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]-5[/color], also reduce the penalty to Maximum Fatigue from your main-hand weapon by [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSavageStrength].Tooltip = ::Const.Strings.PerkDescription.PTRSavageStrength;

::Const.Strings.PerkDescription.PTRSwordmasterBladeDancer = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Non-hybrid Sword[/color]\nLet's Dance!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When using a non-fencing sword, the Action Point costs of sword skills is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color].\n• Each subsequent attack each turn builds [color=" + this.Const.UI.Color.NegativeValue + "]15%[/color] more Fatigue.\n• Allows \'Kata Step\' to be usable even while holding something, e.g. a Shield, in your offhand.\n• \'Kata Step\' costs [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] fewer Action Points and builds [color=" + this.Const.UI.Color.PositiveValue + "]2[/color] less Fatigue, both down to a minimum of 0.\n\n[color=" + this.Const.UI.Color.NegativeValue + "]You can only pick ONE perk from the Swordmaster perk group.[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwordmasterBladeDancer].Tooltip = ::Const.Strings.PerkDescription.PTRSwordmasterBladeDancer;

::Const.Strings.PerkDescription.PTRSwordmasterReaper = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Non-hybrid Sword[/color]\nBring in the harvest!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The Action Point costs of AoE sword skills is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]2[/color].\n\n[color=" + this.Const.UI.Color.NegativeValue + "]You can only pick ONE perk from the Swordmaster perk group.[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwordmasterReaper].Tooltip = ::Const.Strings.PerkDescription.PTRSwordmasterReaper;

::Const.Strings.PerkDescription.PTRSwordmasterPrecise = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Non-hybrid Sword[/color]\nLet me show you how to thread a needle... blindfolded!\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The bonuses of the \'Swordmaster\'s Training\' or \'Swordmaster\'s Finesse\' effect is start counting from level 1.\n• While wielding a Fencing Sword, the efficacy of the target\'s remaining armor after an attack to reduce received Hitpoints damage is halved.\n\n[color=" + this.Const.UI.Color.NegativeValue + "]You can only pick ONE perk from the Swordmaster perk group.[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwordmasterPrecise].Tooltip = ::Const.Strings.PerkDescription.PTRSwordmasterPrecise;

::Const.Strings.PerkDescription.PTRSwordmasterJuggernaut = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Non-hybrid two-handed Sword[/color]\nThere\'s a fine line between bravery and stupidity.\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Each single-target attack with a two-handed sword additionally does [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] of its damage to a random enemy adjacent to the target.\n\n[color=" + this.Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 7 AP and builds 25 Fatigue.\n• Immediately gain the weak \'Indomitable\' effect that lasts until your next turn.\n• Charge towards a tile up to 2 tiles away, staggering all enemies adjacent to that tile and performing a free attack against a random enemy that does [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] increased damage (allows you to close the gap with targets up to 3 tiles away).\n• Cannot be used when engaged in melee.\n\n[color=" + this.Const.UI.Color.Active + "][u]Active: Indomitable[/u][/color]\n• 7 AP and builds 25 Fatigue.\n• Become immune to being knocked back, grabbed or stunned.\n• Reduce damage taken by [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color].\n• The effects last until your next turn.\n\n[color=" + this.Const.UI.Color.NegativeValue + "]You can only pick ONE perk from the Swordmaster perk group.[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwordmasterJuggernaut].Tooltip = ::Const.Strings.PerkDescription.PTRSwordmasterJuggernaut;

::Const.Strings.PerkDescription.PTRSwordmasterGrappler = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Non-hybrid Sword[/color]\nYou have to fight for your place in this world.\n\n[color=" + this.Const.UI.Color.Active + "][u]Active: Kick[/u][/color]\nCosts 4 AP and builds 15 Fatigue.\n• Knocks back and staggers the target.\n• When using a two-handed sword or double-gripping a one-handed sword, the Action Point cost is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] and the Fatigue Cost by [color=" + this.Const.UI.Color.PositiveValue + "]5[/color].\n\n[color=" + this.Const.UI.Color.Active + "][u]Active: Push Through[/u][/color]\nCosts 4 AP and builds 20 Fatigue.\n• Allows you to knock back and stagger a target while moving into their tile in one action.\n\n[color=" + this.Const.UI.Color.Active + "][u]Active: Tackle[/u][/color]\nCosts 6 AP and builds 20 Fatigue.\n• Requires a two-handed or double-gripped one-handed sword. Allows you to exchange positions with and stagger an adjacent target.\n\n[color=" + this.Const.UI.Color.NegativeValue + "]You can only pick ONE perk from the Swordmaster perk group.[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.PTRSwordmasterGrappler].Tooltip = ::Const.Strings.PerkDescription.PTRSwordmasterGrappler;

::Const.Strings.PerkDescription.STRPhalanx = "[color=" + this.Const.UI.Color.NegativeValue + "]Requires: Shield[/color]\n\n[color=" + this.Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• When engaged in melee and equipped with a Shield, gain [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] Melee Defense per adjacent ally holding a Shield who is also engaged in melee.\n• When holding a Shield with a Spear or sword, gain a bonus [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] Melee Skill per adjacent ally holding a Shield who is also engaged in melee.\n\n[color=#0b0084]From the Shield perk group[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.STRPhalanx].Tooltip = ::Const.Strings.PerkDescription.STRPhalanx;

::Const.Strings.PerkDescription.STRCoverAlly = "[color=" + this.Const.UI.Color.NegativeValue + "]Requires: Shield[/color]\n\n[color=" + this.Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 4 AP and builds 20 Fatigue.\n• Allows you to target an adjacent ally and allow them to move [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] tile, ignoring Zone of Control, on their next turn.\n• While under cover, the target ally\'s position in the turn order in the next round is determined as if they had [color=" + this.Const.UI.Color.PositiveValue + "]+2000[/color] Initiative.\n• The effect only remains active as long as you are adjacent to that ally.\n\n[color=#0b0084]From the Shield perk group[/color]";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.STRCoverAlly].Tooltip = ::Const.Strings.PerkDescription.STRCoverAlly;

::Const.Strings.PerkDescription.LegendHairSplitter = "Years of practice throwing things at apples above heads have granted a magnetic attraction to the cranium.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+30%[/color] chance to hit the head.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendHairSplitter].Tooltip = ::Const.Strings.PerkDescription.LegendHairSplitter;
